# Objective: 
MI, MACE, HF, CAD, stroke before that by any margin

# Packages

In [1]:
import pandas as pd 
import numpy as np 
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime
%matplotlib inline

# Dataset

In [2]:
#primary care
pri_cli = pd.read_csv('../primary_care/gp_clinical.txt', sep = '\t', encoding='ISO-8859-1')

In [3]:
#secondary care
sec_cli = pd.read_csv('../primary_care/ukb41199.csv', usecols=[0,
                          3239, 3240, 3241, 3242, 3243, 3244, 3245, 3246, 3247, 
                          3248, 3249, 3250, 8330, 8331, 8332, 8333, 8334, 8335,
                          8336, 8337, 8338, 8339, 8340, 8341, 8342, 8343, 8346])

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (8330,8332,8334,8336,8338,8340,8342) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
total_patients = set(list(sec_cli.eid.unique()) + list(pri_cli.eid.unique()))

In [6]:
len(total_patients)

502505

In [7]:
sec_pri_icd10= [0,] + list(range(6693, 6759))
sec_pri_icd9= [0,] + list(range(6759, 6787))
sec_sec_icd10= [0,] + list(range(6787, 6971))
sec_sec_icd9= [0,] + list(range(6971, 7001))

In [8]:
sec_pri10_diag = pd.read_csv('../primary_care/ukb41199.csv', usecols=sec_pri_icd10)

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (6700,6701,6702,6703,6704,6705,6706,6707,6708,6709,6710,6711,6712,6713,6714,6715,6716,6717,6718,6719,6720,6721,6722,6723,6724,6725,6726,6727,6728,6729,6730,6731,6732,6733,6734,6735,6736,6737,6738,6739,6740,6741,6742,6743,6744,6745,6746,6747,6748,6749,6750,6751,6752,6753,6754,6755,6756,6757,6758) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
sec_pri9_diag = pd.read_csv('../primary_care/ukb41199.csv', usecols=sec_pri_icd9)

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (6759,6760,6761,6762,6763,6764,6765,6766,6767,6768,6769,6770,6771,6772,6773,6774,6775,6776,6781) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [10]:
sec_sec10_diag = pd.read_csv('../primary_care/ukb41199.csv', usecols=sec_sec_icd10)
sec_sec9_diag = pd.read_csv('../primary_care/ukb41199.csv', usecols=sec_sec_icd9)

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (6796,6797,6798,6799,6800,6801,6802,6803,6804,6805,6806,6807,6808,6809,6810,6811,6812,6813,6814,6815,6816,6817,6818,6819,6820,6821,6822,6823,6824,6825,6826,6827,6828,6829,6830,6831,6832,6833,6834,6835,6836,6837,6838,6839,6840,6841,6842,6843,6844,6845,6846,6847,6848,6849,6850,6851,6852,6853,6854,6855,6856,6857,6858,6859,6860,6861,6862,6863,6864,6865,6866,6867,6868,6869,6870,6871,6872,6873,6874,6875,6876,6877,6878,6879,6880,6881,6882,6883,6884,6885,6886,6887,6888,6889,6890,6891,6892,6893,6894,6895,6896,6897,6898,6899,6900,6901,6902,6903,6904,6905,6906,6907,6908,6909,6910,6911,6912,6913,6914,6915,6916,6917,6918,6919,6920,6921,6922,6923,6924,6925,6926,6927,6928,6929,6930,6931,6932,6933,6934,6935,6936,6937,6938,6939,6940,6941,6942,6943,6944,6945,6946,6947,6948,6949,6950,6951,6952,6953,6954,6955,6956,6957,6958,6959,6960,6961,6962,6963,6964,6965,6966,6967,6968,6969,6970) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (6971,6972,6973,6974,6975,6976,6977,6978,6979,6980,6981,6982,6983,6984,6985,6986,6987,6988,6989,6990,6991,6992,6993,6994,6995,6996,6999,7000) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [11]:
sec_pri10_date = pd.read_csv('../primary_care/ukb41199.csv', usecols=([0,] + list(range(7450,7516))))
sec_pri9_date = pd.read_csv('../primary_care/ukb41199.csv', usecols=([0,] + list(range(7516,7544))))

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (7457,7458,7459,7460,7461,7462,7463,7464,7465,7466,7467,7468,7469,7470,7471,7472,7473,7474,7475,7476,7477,7478,7479,7480,7481,7482,7483,7484,7485,7486,7487,7488,7489,7490,7491,7492,7493,7494,7495,7496,7497,7498,7499,7500,7501,7502,7503,7504,7505,7506,7507,7508,7509,7510,7511,7512,7513,7514,7515) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (7516,7517,7518,7519,7520,7521,7522,7523,7524,7525,7526,7527,7528,7529,7530,7531,7532,7533,7534,7535,7536,7537,7538,7539,7540,7541,7542,7543) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [12]:
#demo
pri_demo = pd.read_csv('../primary_care/ukb41199.csv', usecols=[0,6])

In [13]:
#diag code
diag_codes = pd.read_excel('../primary_care/ProposedDiagnosisCodes.xlsx', sheet_name = "diag")
icd10_codes = pd.read_excel('../primary_care/ProposedDiagnosisCodes.xlsx', sheet_name = "icd10")
icd9_codes = pd.read_excel('../primary_care/ProposedDiagnosisCodes.xlsx', sheet_name = "icd9")

#drop duplicates 
diag_codes_summ = diag_codes[['READV2_CODE', 'READV3_CODE', 'Condition']].drop_duplicates(subset=None, keep='first', inplace=False)

# Diagnosis coding

## Pri

In [14]:
disease = {
    'stroke' : {
        'read2': list(diag_codes[diag_codes['Condition']== 'Stroke']['READV2_CODE']),
        'read3': list(diag_codes[diag_codes['Condition']== 'Stroke']['READV3_CODE'])
    },
    'HF' : {
        'read2': list(diag_codes[diag_codes['Condition']== 'HF']['READV2_CODE']),
        'read3': list(diag_codes[diag_codes['Condition']== 'HF']['READV3_CODE'])
    }, 
    'CAD' : {
        'read2': list(diag_codes[diag_codes['Condition']== 'CAD']['READV2_CODE']),
        'read3': list(diag_codes[diag_codes['Condition']== 'CAD']['READV3_CODE'])
    },
    'MI' : {
        'read2': list(diag_codes[diag_codes['Condition']== 'MI']['READV2_CODE']),
        'read3': list(diag_codes[diag_codes['Condition']== 'MI']['READV3_CODE'])
    },
    'precursor' : {
        'read2': list(diag_codes[diag_codes['Condition']== 'precursor']['READV2_CODE']),
        'read3': list(diag_codes[diag_codes['Condition']== 'precursor']['READV3_CODE'])
    },
    'TIA' : {
        'read2': list(diag_codes[diag_codes['Condition']== 'TIA']['READV2_CODE']),
        'read3': list(diag_codes[diag_codes['Condition']== 'TIA']['READV3_CODE'])
    },
    'Afib' : {
        'read2': list(diag_codes[diag_codes['Condition']== 'Afib']['READV2_CODE']),
        'read3': list(diag_codes[diag_codes['Condition']== 'Afib']['READV3_CODE'])
    },
    'all' : {
        'read2': list(diag_codes['READV2_CODE'].values),
        'read3': list(diag_codes['READV3_CODE'].values)
    }
}

In [15]:
#isolating codes from primary care
diagnosed = pri_cli[pri_cli['read_2'].isin(disease['all']['read2'])| pri_cli['read_3'].isin(disease['all']['read3'])]

In [16]:
#adding condition codes
condition = []
for i in range(len(diagnosed['eid'])):
    if type(diagnosed.iloc[i]['read_2']) == str:
        key = diagnosed.iloc[i]['read_2']
        a = diag_codes_summ[diag_codes_summ['READV2_CODE'] == key]['Condition'].values[0]
        condition.append(a)
    elif type(diagnosed.iloc[i]['read_3']) == str: 
        key = diagnosed.iloc[i]['read_3']
        a = diag_codes_summ[diag_codes_summ['READV3_CODE'] == key]['Condition'].values[0]
        condition.append(a)
    else:
        condition.append(np.nan)

In [17]:
diagnosed['condition'] = condition

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [18]:
diagnosed

,eid,data_provider,event_dt,read_2,read_3,value1,value2,value3,condition
10678,1000421,3,27/05/2010,NaN,XE0VK,NaN,NaN,NaN,TIA
10714,1000421,3,04/10/2010,NaN,XE2uV,NaN,NaN,NaN,CAD
10715,1000421,3,04/10/2010,NaN,XE2uV,NaN,NaN,NaN,CAD
12996,1000530,3,26/03/2012,NaN,XE0VK,NaN,NaN,NaN,TIA
13007,1000530,3,31/03/2012,NaN,XE0VK,NaN,NaN,NaN,TIA
...,...,...,...,...,...,...,...,...,...
123600655,6022686,3,11/05/2011,NaN,XE2aB,NaN,NaN,NaN,Stroke
123600772,6022686,3,21/05/2012,NaN,XE2aB,NaN,NaN,NaN,Stroke
123603082,6022795,2,19/01/2015,G5730,NaN,NaN,NaN,NaN,Afib
123603411,6022831,3,01/07/2005,NaN,XE0VK,NaN,NaN,NaN,TIA
123609034,6023090,3,29/07/2005,NaN,XE2uV,NaN,NaN,NaN,CAD

In [19]:
# remove duplicates
diagnosed.drop_duplicates(subset=None, keep='first', inplace=True)

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [20]:
# setting the list with (date, condition, 'pri')
pri_date_diag = []
for i in range(len(diagnosed['eid'])):
    a = [diagnosed.iloc[i]['event_dt'], diagnosed.iloc[i]['condition'].lower(), 'pri']
    pri_date_diag.append(a)

In [21]:
diagnosed['pri_date_diag'] = pri_date_diag

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [22]:
diagnosed

,eid,data_provider,event_dt,read_2,read_3,value1,value2,value3,condition,pri_date_diag
10678,1000421,3,27/05/2010,NaN,XE0VK,NaN,NaN,NaN,TIA,"[27/05/2010, tia, pri]"
10714,1000421,3,04/10/2010,NaN,XE2uV,NaN,NaN,NaN,CAD,"[04/10/2010, cad, pri]"
12996,1000530,3,26/03/2012,NaN,XE0VK,NaN,NaN,NaN,TIA,"[26/03/2012, tia, pri]"
13007,1000530,3,31/03/2012,NaN,XE0VK,NaN,NaN,NaN,TIA,"[31/03/2012, tia, pri]"
22383,1000660,3,01/01/1983,NaN,XE2uV,NaN,NaN,NaN,CAD,"[01/01/1983, cad, pri]"
...,...,...,...,...,...,...,...,...,...,...
123600655,6022686,3,11/05/2011,NaN,XE2aB,NaN,NaN,NaN,Stroke,"[11/05/2011, stroke, pri]"
123600772,6022686,3,21/05/2012,NaN,XE2aB,NaN,NaN,NaN,Stroke,"[21/05/2012, stroke, pri]"
123603082,6022795,2,19/01/2015,G5730,NaN,NaN,NaN,NaN,Afib,"[19/01/2015, afib, pri]"
123603411,6022831,3,01/07/2005,NaN,XE0VK,NaN,NaN,NaN,TIA,"[01/07/2005, tia, pri]"
123609034,6023090,3,29/07/2005,NaN,XE2uV,NaN,NaN,NaN,CAD,"[29/07/2005, cad, pri]"

In [23]:
#order by id
pri_records = diagnosed.groupby('eid').agg(list).reset_index()

In [24]:
pri_records.iloc[21]['pri_date_diag']

[['01/09/2007', 'mi', 'pri'],
 ['17/09/2007', 'mi', 'pri'],
 ['04/10/2007', 'mi', 'pri'],
 ['23/10/2007', 'mi', 'pri'],
 ['04/12/2007', 'mi', 'pri'],
 ['07/12/2007', 'mi', 'pri'],
 ['31/01/2008', 'cad', 'pri'],
 ['26/02/2008', 'cad', 'pri'],
 ['04/04/2008', 'cad', 'pri'],
 ['02/06/2008', 'cad', 'pri'],
 ['03/11/2008', 'cad', 'pri'],
 ['05/02/2009', 'cad', 'pri'],
 ['16/11/2009', 'cad', 'pri'],
 ['02/12/2010', 'cad', 'pri'],
 ['11/05/2011', 'cad', 'pri'],
 ['13/12/2011', 'cad', 'pri'],
 ['07/12/2012', 'cad', 'pri'],
 ['11/09/2013', 'cad', 'pri'],
 ['24/09/2014', 'cad', 'pri']]

## Secondary codes

In [25]:
ICD = {
    10: {
        'stroke': list(icd10_codes[icd10_codes['diagnosis'] == 'stroke']['ICD10']),
        'tia': list(icd10_codes[icd10_codes['diagnosis'] == 'tia']['ICD10']),
        'haemorrhage': list(icd10_codes[icd10_codes['diagnosis'] == 'haemorrhage']['ICD10']),
        'cad': list(icd10_codes[icd10_codes['diagnosis'] == 'cad']['ICD10']),
        'mi': list(icd10_codes[icd10_codes['diagnosis'] == 'haemorrhage']['ICD10']),
        'hf': list(icd10_codes[icd10_codes['diagnosis'] == 'hf']['ICD10']),
        'afib': list(icd10_codes[icd10_codes['diagnosis'] == 'afib']['ICD10']),
        'all': list(icd10_codes['ICD10'])
    },
    9: {
        'stroke': list(icd9_codes[icd9_codes['diagnosis'] == 'stroke']['ICD9']),
        'tia': list(icd9_codes[icd9_codes['diagnosis'] == 'tia']['ICD9']),
        'haemorrhage': list(icd9_codes[icd9_codes['diagnosis'] == 'haemorrhage']['ICD9']),
        'cad': list(icd9_codes[icd9_codes['diagnosis'] == 'cad']['ICD9']),
        'mi': list(icd9_codes[icd9_codes['diagnosis'] == 'haemorrhage']['ICD9']),
        'hf': list(icd9_codes[icd9_codes['diagnosis'] == 'hf']['ICD9']),
        'afib': list(icd9_codes[icd9_codes['diagnosis'] == 'afib']['ICD9']),
        'all': list(icd9_codes['ICD9'])
    }
}

In [26]:
sec_pri10_date.columns = ['eid',] + list(map(lambda x: str(x), range(0,66)))
sec_pri10_diag.columns = ['eid',] + list(map(lambda x: str(x), range(0,66)))

In [27]:
sec_pri10 = pd.merge(sec_pri10_date, sec_pri10_diag, on= 'eid', how='inner')

In [28]:
sec_pri9_date.columns = ['eid',] + list(map(lambda x: str(x), range(0,28)))
sec_pri9_diag.columns = ['eid',] + list(map(lambda x: str(x), range(0,28)))

In [29]:
sec_pri9 = pd.merge(sec_pri9_date, sec_pri9_diag, on= 'eid', how='inner')

In [30]:
sec_pri10

,eid,0_x,1_x,2_x,3_x,4_x,5_x,6_x,7_x,8_x,...,56_y,57_y,58_y,59_y,60_y,61_y,62_y,63_y,64_y,65_y
0,1000019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000022,2013-12-28,2000-10-27,2000-11-18,2000-11-29,2008-04-02,2005-10-19,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1000035,2014-12-09,2014-12-08,2012-11-28,2013-02-16,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000046,1998-10-01,1997-11-28,2002-05-29,1997-09-01,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1000054,2014-02-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502500,6025018,1997-04-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502501,6025023,2008-01-28,2010-08-09,2014-05-28,2008-01-16,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502502,6025031,2016-08-05,2016-08-18,2006-02-08,2008-09-12,2011-03-24,2008-02-16,2000-05-04,2017-03-07,2007-12-18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502503,6025040,2004-07-15,2008-03-08,2011-02-09,2001-06-15,1999-06-18,2014-09-16,2011-03-16,2006-03-15,2004-11-30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502504,6025057,1999-01-08,2009-06-04,2004-05-29,2010-02-05,1999-05-21,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
sec_pri10.shape

(502505, 133)

In [31]:
def aggregate(df, name):
    cols = list(df.columns)[1:]
    collen = len(cols)
    result = []
    for i in range(df.shape[0]):
        subresult = []
        for x in cols: 
            temp = df.iloc[i][x]
            if type(x) == str:
                subresult.append(x)
    df[name] = result
    print('fin')

In [32]:
sec_pri10_date['combined'] = sec_pri10_date.values.tolist()
sec_pri9_date['combined'] = sec_pri9_date.values.tolist()
sec_pri10_diag['combined'] = sec_pri10_diag.values.tolist()
sec_pri9_diag['combined'] = sec_pri9_diag.values.tolist()

In [33]:
sec_pri10 = pd.merge(sec_pri10_date[['eid','combined']], sec_pri10_diag[['eid','combined']], on = 'eid', how = 'inner')
sec_pri9 = pd.merge(sec_pri9_date[['eid','combined']], sec_pri9_diag[['eid','combined']], on = 'eid', how = 'inner')

In [34]:
sec_pri10['datet'] = [item[1:] for item in sec_pri10['combined_x']]

In [35]:
sec_pri10['diagt'] = [item[1:] for item in sec_pri10['combined_y']]

In [36]:
def removenan(df): 
    datet2 = []
    diagt2 = []
    for i in range(df.shape[0]):
        temp1 = [x for x in df.iloc[i]['datet'] if type(x) != float]
        temp2 = [x for x in df.iloc[i]['diagt'] if type(x) != float]
        datet2.append(temp1)
        diagt2.append(temp2)
    df['datet2'] = datet2
    df['diagt2'] = diagt2

In [37]:
def zipper(df):
    result = []
    for i in range(df.shape[0]):
        temp = list(map(list, zip(df.iloc[i]['datet2'], df.iloc[i]['diagt2'])))
        result.append(temp)
    df['zipped'] = result
    print('end')

In [38]:
sec_pri9['datet'] = [item[1:] for item in sec_pri9['combined_x']]
sec_pri9['diagt'] = [item[1:] for item in sec_pri9['combined_y']]

In [39]:
removenan(sec_pri10)
zipper(sec_pri10)

end

In [40]:
removenan(sec_pri9)
zipper(sec_pri9)

end

# Secondary Records

## secondary ICD

In [41]:
sec_pri9['len'] = [len(x) for x in sec_pri9['zipped']]
sec_pri9_diag = sec_pri9[sec_pri9['len'] > 0]

In [42]:
sec_pri10['len'] = [len(x) for x in sec_pri10['zipped']]
sec_pri10_diag = sec_pri10[sec_pri10['len'] > 0]

In [43]:
def icdsearch(df, code):
    result = []
    if code == 10:
        for x in df['zipped']:
            temp = []
            if len(x) > 0:
                for y in x:
                    q = y[1][:3]
                    if q in ICD[10]['all']:
                        diag = icd10_codes[icd10_codes['ICD10'].str.contains(q)]['diagnosis'].values[0]
                        temp.append([datetime.strptime(y[0], '%Y-%m-%d').strftime('%d/%m/%Y'), diag, 'sec'])
            result.append(temp)
    elif code == 9:
        for x in df['zipped']:
            temp = []
            if len(x) > 0:
                for y in x:
                    q = str(y[1])[:3]
                    if q in ICD[9]['all']:
                        diag = icd9_codes[icd9_codes['ICD9'].str.contains(q)]['diagnosis'].values[0]
                        temp.append([datetime.strptime(y[0], '%Y-%m-%d').strftime('%d/%m/%Y'), diag, 'sec'])
            result.append(temp)
    df['coded'] = result
    print('end')

In [44]:
icdsearch(sec_pri10_diag,10)
icdsearch(sec_pri9_diag,9)

end
end

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [45]:
icdsearch(sec_pri10_diag,10)

end

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [46]:
sec_pri10_diag['codedlen'] = [len(x) for x in sec_pri10_diag['coded']]
sec_pri10_cvd = sec_pri10_diag[sec_pri10_diag['codedlen'] > 0]

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [47]:
sec_pri9_diag['codedlen'] = [len(x) for x in sec_pri9_diag['coded']]
sec_pri9_cvd = sec_pri9_diag[sec_pri9_diag['codedlen'] > 0]

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [48]:
sec_pri = sec_pri10_cvd[['eid','coded']]

## Self Reported

In [49]:
sec_cli.shape

(502505, 28)

In [50]:
sec_cli.columns = ['eid', 'cardiac_0_a', 'cardiac_0_b', 'cardiac_0_c', 
                    'cardiac_0_d', 'cardiac_1_a', 'cardiac_1_b', 
                    'cardiac_1_c', 'cardiac_1_d', 'cardiac_2_a', 
                    'cardiac_2_b', 'cardiac_2_c', 'cardiac_2_d',
                    'MI_date', 'MI_source', 'STEMI_date', 
                    'STEMI_source', 'NSTEMI_date',
                    'NSTEMI_source', 'stroke_date', 'stroke_source',
                    'istroke_date', 'istroke_source', 
                    'intracerb_rrhage_d', 'intracerb_rrhage_s',
                    'subara_rrhage_d', 'subara_rrhage_s', 'gp_event_n'
       ]

In [51]:
cardiac_sec = sec_cli[(sec_cli.iloc[:, 1]==3.0) |
   (sec_cli.iloc[:, 2]==3.0) | 
   (sec_cli.iloc[:, 3]==3.0) |
   (sec_cli.iloc[:, 4]==3.0) |
   (sec_cli.iloc[:, 5]==3.0) |
   (sec_cli.iloc[:, 6]==3.0) |
   (sec_cli.iloc[:, 7]==3.0) |
   (sec_cli.iloc[:, 8]==3.0) |
   (sec_cli.iloc[:, 9]==3.0) |
   (sec_cli.iloc[:, 10]==3.0) |
   (sec_cli.iloc[:, 11]==3.0) |
   (sec_cli.iloc[:, 12]==3.0) |
   (sec_cli.iloc[:, 1]==1.0) |
   (sec_cli.iloc[:, 2]==1.0) | 
   (sec_cli.iloc[:, 3]==1.0) |
   (sec_cli.iloc[:, 4]==1.0) |
   (sec_cli.iloc[:, 5]==1.0) |
   (sec_cli.iloc[:, 6]==1.0) |
   (sec_cli.iloc[:, 7]==1.0) |
   (sec_cli.iloc[:, 8]==1.0) |
   (sec_cli.iloc[:, 9]==1.0) |
   (sec_cli.iloc[:, 10]==1.0) |
   (sec_cli.iloc[:, 11]==1.0) |
   (sec_cli.iloc[:, 12]==1.0)
  ]

In [52]:
#incidences
stroke0instance = []
stroke1instance = []
stroke2instance = []

# stroke is coded as 3
for i in range(0,len(cardiac_sec['eid'])): 
    if cardiac_sec.iloc[i]['cardiac_0_a']==3.0 or cardiac_sec.iloc[i]['cardiac_0_b']==3.0 or cardiac_sec.iloc[i]['cardiac_0_c']==3.0 or cardiac_sec.iloc[i]['cardiac_0_d']==3.0:
        stroke0instance.append(1)
    else: 
        stroke0instance.append(0)
    if cardiac_sec.iloc[i]['cardiac_1_a'] ==3.0 or cardiac_sec.iloc[i]['cardiac_1_b']==3.0 or cardiac_sec.iloc[i]['cardiac_1_c']==3.0 or cardiac_sec.iloc[i]['cardiac_1_d']==3.0:
        stroke1instance.append(1)
    else:
        stroke1instance.append(0)
    if cardiac_sec.iloc[i]['cardiac_2_a'] ==3.0 or cardiac_sec.iloc[i]['cardiac_2_b']==3.0 or cardiac_sec.iloc[i]['cardiac_2_c']==3.0 or cardiac_sec.iloc[i]['cardiac_2_d']==3.0:
        stroke2instance.append(1)
    else:
        stroke2instance.append(0)

In [53]:
HA0instance = []
HA1instance = []
HA2instance = []

for i in range(0,len(cardiac_sec['eid'])): 
    if cardiac_sec.iloc[i]['cardiac_0_a']==1.0 or cardiac_sec.iloc[i]['cardiac_0_b']==1.0 or cardiac_sec.iloc[i]['cardiac_0_c']==1.0 or cardiac_sec.iloc[i]['cardiac_0_d']==1.0:
        HA0instance.append(1)
    else: 
        HA0instance.append(0)
    if cardiac_sec.iloc[i]['cardiac_1_a'] ==1.0 or cardiac_sec.iloc[i]['cardiac_1_b']==1.0 or cardiac_sec.iloc[i]['cardiac_1_c']==1.0 or cardiac_sec.iloc[i]['cardiac_1_d']==1.0:
        HA1instance.append(1)
    else:
        HA1instance.append(0)
    if cardiac_sec.iloc[i]['cardiac_2_a'] ==1.0 or cardiac_sec.iloc[i]['cardiac_2_b']==1.0 or cardiac_sec.iloc[i]['cardiac_2_c']==1.0 or cardiac_sec.iloc[i]['cardiac_2_d']==1.0:
        HA2instance.append(1)
    else:
        HA2instance.append(0)

In [54]:
cardiac_sec['stroke0instance'] = stroke0instance
cardiac_sec['stroke1instance'] = stroke1instance
cardiac_sec['stroke2instance'] = stroke2instance 
cardiac_sec['HA0instance'] = HA0instance
cardiac_sec['HA1instance'] = HA1instance
cardiac_sec['HA2instance'] = HA2instance

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [55]:
cardiac_sec['stroke'] = (cardiac_sec['stroke0instance'] + cardiac_sec['stroke1instance']+ cardiac_sec['stroke2instance']) > 0

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [56]:
cardiac_sec['ha'] = (cardiac_sec['HA0instance'] + cardiac_sec['HA1instance']+ cardiac_sec['HA2instance']) > 0

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [57]:
# changing date formats
cardiac_sec['f_MI_date'] = [np.nan if type(x) == float else datetime.strptime(x, '%Y-%m-%d').strftime('%d/%m/%Y') for x in cardiac_sec['MI_date']]

cardiac_sec['f_stroke_date'] = [np.nan if type(x) == float else datetime.strptime(x, '%Y-%m-%d').strftime('%d/%m/%Y') for x in cardiac_sec['stroke_date']]

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [58]:
date_diag = []

for i in range(len(cardiac_sec['eid'])):
    recorded = []
    if cardiac_sec.iloc[i]['stroke'] == True: 
        if type(cardiac_sec.iloc[i]['f_stroke_date'])== float:
            recorded.append([np.nan])
        else:
            stroke_stat = [cardiac_sec.iloc[i]['f_stroke_date'], 'Stroke']
            recorded.append(stroke_stat)
            
    if cardiac_sec.iloc[i]['ha'] == True: 
        if type(cardiac_sec.iloc[i]['f_MI_date']) == float:
            recorded.append([np.nan])
        else:
            mi_stat = [cardiac_sec.iloc[i]['f_MI_date'], 'MI']
            recorded.append(mi_stat)
            
    date_diag.append(recorded)

In [59]:
cardiac_sec['date_diag'] = date_diag

/Users/michelleng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [60]:
cardiac_summ = cardiac_sec[['eid',
'stroke',  
'ha', 
'date_diag']]

In [61]:
cardiac_summ

            eid  stroke     ha               date_diag
5       1000063    True  False  [[09/01/2003, Stroke]]
28      1000291   False   True      [[23/07/2003, MI]]
57      1000584   False   True      [[05/11/1996, MI]]
109     1001104   False   True                 [[nan]]
115     1001162    True  False                 [[nan]]
...         ...     ...    ...                     ...
502415  6024161    True  False                 [[nan]]
502420  6024215    True  False  [[04/08/2002, Stroke]]
502479  6024805    True  False  [[06/07/2005, Stroke]]
502488  6024898   False   True      [[24/01/2005, MI]]
502503  6025040   False   True      [[12/01/2006, MI]]

[18875 rows x 4 columns]

# Primary care and Secondary care merge

In [49]:
all_care = pd.merge(sec_pri, pri_records, how= 'outer', on = ['eid', 'eid'])

In [50]:
all_care

,eid,coded,data_provider,event_dt,read_2,read_3,value1,value2,value3,condition,pri_date_diag
0,1000255,"[[02/09/2015, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000421,"[[04/08/2010, cad, sec], [27/05/2010, stroke, ...","[3, 3]","[27/05/2010, 04/10/2010]","[nan, nan]","[XE0VK, XE2uV]","[nan, nan]","[nan, nan]","[nan, nan]","[TIA, CAD]","[[27/05/2010, tia, pri], [04/10/2010, cad, pri]]"
2,1000466,"[[11/06/2002, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000584,"[[16/06/1997, cad, sec], [19/10/2004, afib, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1000674,"[[31/05/2006, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
53318,6020725,NaN,"[3, 3]","[01/01/1993, 18/09/2003]","[nan, nan]","[G66.., XE0VK]","[nan, nan]","[nan, nan]","[nan, nan]","[Stroke, TIA]","[[01/01/1993, stroke, pri], [18/09/2003, tia, ..."
53319,6021009,NaN,[3],[09/06/2016],[nan],[G5730],[nan],[nan],[nan],[Afib],"[[09/06/2016, afib, pri]]"
53320,6021143,NaN,"[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...","[20/01/2005, 11/02/2005, 07/04/2005, 21/11/200...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[X00DW, X00DW, X00DW, X00DW, X00DW, X00DW, X00...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, ...","[[20/01/2005, tia, pri], [11/02/2005, tia, pri..."
53321,6022795,NaN,[2],[19/01/2015],[G5730],[nan],[nan],[nan],[nan],[Afib],"[[19/01/2015, afib, pri]]"
53322,6023090,NaN,[3],[29/07/2005],[nan],[XE2uV],[nan],[nan],[nan],[CAD],"[[29/07/2005, cad, pri]]"

In [51]:
all_care['pri_date_diag'] = all_care['pri_date_diag'].apply(lambda x: x if isinstance(x, list) else [])

In [52]:
all_care['coded'] = all_care['coded'].apply(lambda x: x if isinstance(x, list) else [])

In [53]:
#. combine secondary and primary care dates
all_care['record_diag'] = all_care['coded'] + all_care['pri_date_diag']

In [54]:
records = pd.merge(all_care, pri_demo, how= 'left', on = ['eid', 'eid'])

In [55]:
records

,eid,coded,data_provider,event_dt,read_2,read_3,value1,value2,value3,condition,pri_date_diag,record_diag,34-0.0
0,1000255,"[[02/09/2015, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[[02/09/2015, cad, sec]]",1948.0
1,1000421,"[[04/08/2010, cad, sec], [27/05/2010, stroke, ...","[3, 3]","[27/05/2010, 04/10/2010]","[nan, nan]","[XE0VK, XE2uV]","[nan, nan]","[nan, nan]","[nan, nan]","[TIA, CAD]","[[27/05/2010, tia, pri], [04/10/2010, cad, pri]]","[[04/08/2010, cad, sec], [27/05/2010, stroke, ...",1952.0
2,1000466,"[[11/06/2002, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[[11/06/2002, cad, sec]]",1949.0
3,1000584,"[[16/06/1997, cad, sec], [19/10/2004, afib, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[[16/06/1997, cad, sec], [19/10/2004, afib, sec]]",1951.0
4,1000674,"[[31/05/2006, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[[31/05/2006, cad, sec]]",1944.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53318,6020725,[],"[3, 3]","[01/01/1993, 18/09/2003]","[nan, nan]","[G66.., XE0VK]","[nan, nan]","[nan, nan]","[nan, nan]","[Stroke, TIA]","[[01/01/1993, stroke, pri], [18/09/2003, tia, ...","[[01/01/1993, stroke, pri], [18/09/2003, tia, ...",1942.0
53319,6021009,[],[3],[09/06/2016],[nan],[G5730],[nan],[nan],[nan],[Afib],"[[09/06/2016, afib, pri]]","[[09/06/2016, afib, pri]]",1949.0
53320,6021143,[],"[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...","[20/01/2005, 11/02/2005, 07/04/2005, 21/11/200...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[X00DW, X00DW, X00DW, X00DW, X00DW, X00DW, X00...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, ...","[[20/01/2005, tia, pri], [11/02/2005, tia, pri...","[[20/01/2005, tia, pri], [11/02/2005, tia, pri...",1943.0
53321,6022795,[],[2],[19/01/2015],[G5730],[nan],[nan],[nan],[nan],[Afib],"[[19/01/2015, afib, pri]]","[[19/01/2015, afib, pri]]",1948.0
53322,6023090,[],[3],[29/07/2005],[nan],[XE2uV],[nan],[nan],[nan],[CAD],"[[29/07/2005, cad, pri]]","[[29/07/2005, cad, pri]]",1939.0

## unique records and sorting records

In [56]:
# to make records non-duplicative
records['uniq_record_diag'] = [list(map(list,set(map(tuple,x)))) for x in records['record_diag'] if type(x) == list]

In [57]:
sort_record = []

for x in records['uniq_record_diag']:
    
    temp = []
    temp_pri = []
    temp_sec = []
    
    # handling nan
    for i in range(len(x)):
        if x[i] == [np.nan]:
            continue
        else: 
            #changing dates into datetime
            if type(x[i][0]) == str:
                yi0 = datetime.strptime(x[i][0], '%d/%m/%Y')
                yi1 = x[i][1]
                yi2 = x[i][2]
                temp.append([yi0, yi1, yi2])
                
    
    # sorting by dates
    temp.sort(key=lambda x: x[0])

    # append the sorted list
    sort_record.append(temp)

In [58]:
records['sort_record'] = sort_record

## discrepancy coding

In [59]:
records['yr_birth'] = [datetime.strptime(str(int(x)), '%Y') for x in records['34-0.0']]

In [60]:
# removing discrepancy from sort_record
sort_record2 = []
first_record_d =[]
first_record_diag = []
first_stroke_after_d = []
pri_record = []
sec_record = []
first_stroke_type = []

for i in range(records.shape[0]):
    temp = []
    temp_pri = []
    temp_sec = []
    
    recorded = records.iloc[i]['sort_record']
    dob = records.iloc[i]['yr_birth']
    
    if recorded == [np.nan]:
        temp.append([np.nan])
    else:
        
        for x in recorded:
            if x[0] <= dob:
                continue
            else:
                temp.append(x)
                if x[2] == 'pri':
                    temp_pri.append(x)
                elif x[2] == 'sec':
                    temp_sec.append(x)
                    
    sort_record2.append(temp)
    pri_record.append(temp_pri)
    sec_record.append(temp_sec)  
    
    # adding the first recorded dates and diag
    if len(temp) < 1:
        first_record_d.append(np.nan)
        first_record_diag.append(np.nan)
    elif len(temp) == 1:
        if temp[0] == [np.nan]:
            first_record_d.append(np.nan)
            first_record_diag.append(np.nan)
        else:
            first_record_d.append(temp[0][0])
            first_record_diag.append(temp[0][1])
    else:
        first_record_d.append(temp[0][0])
        first_record_diag.append(temp[0][1])
    
    # finding first incidence of stroke after the first incidence
    strokefound = False
    if len(temp) == 1: 
        first_stroke_after_d.append(np.nan)
        first_stroke_type.append(np.nan)
    else:
        for t in temp[1:]:
            if 'stroke' in t or 'tia' in t:
                strokefound = True
                first_stroke_after_d.append(t[0])
                first_stroke_type.append(t[1])
                print(i)
                break
                
        if strokefound == False:
            first_stroke_after_d.append(np.nan)
            first_stroke_type.append(np.nan)

1
7
15
33
67
71
74
85
87
89
101
102
112
121
126
140
145
152
154
165
180
196
203
216
238
286
302
313
316
317
324
331
332
333
338
343
356
391
400
409
421
423
444
445
448
458
460
462
476
510
565
591
592
602
646
652
671
676
680
684
691
696
699
704
706
708
711
720
725
735
741
743
754
777
780
789
802
806
811
815
828
841
844
856
860
863
865
873
894
900
915
916
918
925
948
949
955
964
977
983
992
993
1031
1040
1049
1053
1054
1065
1094
1098
1103
1119
1125
1158
1167
1181
1188
1197
1208
1214
1216
1223
1224
1229
1238
1247
1309
1315
1319
1331
1344
1374
1397
1410
1413
1414
1425
1432
1434
1437
1440
1445
1468
1488
1493
1503
1507
1509
1514
1552
1588
1589
1598
1610
1626
1631
1656
1660
1662
1673
1677
1684
1695
1702
1706
1711
1737
1741
1747
1758
1768
1769
1773
1783
1794
1805
1809
1815
1816
1818
1820
1855
1861
1864
1882
1883
1891
1899
1928
1971
1979
1981
1982
1999
2001
2006
2016
2025
2039
2045
2053
2080
2089
2116
2129
2130
2147
2159
2163
2177
2184
2189
2200
2224
2236
2243
2250
2253
2259
2262
2272
2287
2293
2306
2309
2311
2316
2330
2337
2353
2355
2379
2399
2406
2407
2422
2431
2439
2440
2446
2452
2453
2454
2460
2462
2483
2493
2503
2508
2534
2547
2549
2553
2557
2564
2565
2573
2576
2579
2587
2589
2592
2604
2618
2634
2636
2639
2647
2652
2680
2685
2694
2707
2732
2752
2786
2799
2806
2808
2815
2816
2818
2826
2836
2842
2857
2862
2870
2873
2877
2892
2898
2899
2905
2910
2928
2937
2941
2955
2968
2974
2992
3037
3038
3049
3058
3065
3070
3076
3090
3096
3111
3119
3130
3149
3159
3161
3176
3178
3182
3189
3201
3203
3209
3225
3227
3234
3237
3259
3274
3283
3286
3296
3298
3299
3308
3325
3330
3338
3340
3341
3343
3359
3367
3376
3392
3395
3411
3416
3423
3430
3438
3457
3459
3461
3464
3466
3468
3480
3482
3489
3510
3529
3530
3540
3552
3560
3605
3613
3618
3634
3643
3667
3672
3675
3689
3724
3734
3751
3762
3767
3786
3797
3798
3807
3823
3829
3871
3883
3889
3896
3901
3904
3905
3911
3936
3940
3942
3946
3949
3950
3953
3956
3961
3997
4003
4012
4030
4033
4037
4042
4043
4073
4078
4080
4084
4087
4108
4109
4113
4138
4139
4142
4173
4185
4188
4197
4201
4204
4205
4215
4243
4249
4250
4258
4259
4280
4297
4298
4299
4300
4313
4317
4319
4345
4346
4349
4353
4356
4357
4365
4405
4410
4413
4422
4430
4436
4444
4449
4457
4460
4468
4483
4494
4513
4523
4536
4542
4543
4547
4550
4560
4569
4588
4591
4598
4601
4608
4614
4640
4645
4662
4678
4692
4708
4744
4746
4749
4752
4757
4786
4787
4793
4795
4816
4825
4834
4844
4846
4855
4859
4885
4888
4905
4907
4910
4929
4930
4935
4949
4958
4963
4967
4991
4994
5018
5026
5047
5074
5084
5085
5113
5115
5117
5119
5120
5123
5133
5139
5144
5152
5153
5159
5162
5172
5176
5183
5190
5207
5210
5221
5238
5239
5279
5287
5289
5298
5299
5302
5303
5310
5325
5334
5342
5351
5362
5364
5367
5372
5373
5387
5394
5402
5437
5445
5458
5464
5473
5474
5496
5499
5517
5527
5533
5541
5549
5551
5559
5561
5564
5573
5574
5581
5585
5596
5610
5613
5644
5660
5661
5667
5669
5672
5675
5695
5706
5718
5735
5750
5753
5755
5757
5759
5760
5762
5773
5776
5794
5803
5806
5821
5824
5829
5835
5841
5845
5852
5864
5867
5871
5874
5877
5879
5886
5905
5919
5921
5923
5950
5951
5974
5993
5995
6004
6023
6056
6063
6064
6078
6082
6083
6086
6117
6123
6141
6171
6177
6180
6191
6197
6198
6206
6220
6226
6234
6245
6247
6250
6251
6254
6281
6290
6311
6313
6315
6321
6322
6325
6329
6332
6334
6340
6344
6353
6360
6361
6367
6386
6401
6405
6414
6418
6433
6435
6440
6444
6457
6467
6483
6496
6511
6512
6522
6523
6542
6556
6563
6574
6586
6607
6615
6625
6628
6640
6642
6646
6666
6686
6688
6691
6697
6698
6705
6717
6721
6723
6729
6742
6743
6748
6752
6754
6757
6770
6771
6781
6799
6812
6817
6823
6828
6838
6845
6853
6865
6896
6906
6935
6936
6944
6950
6956
6962
6968
6982
6987
6996
7035
7052
7062
7077
7085
7086
7097
7106
7108
7112
7118
7119
7120
7153
7176
7182
7189
7198
7221
7229
7235
7237
7241
7243
7251
7253
7271
7286
7313
7322
7330
7349
7357
7377
7391
7393
7394
7407
7417
7421
7437
7460
7477
7483
7489
7500
7525
7556
7595
7602
7612
7643
7651
7663
7669
7672
7677
7689
7690
7723
7732
7751
7773
7785
7790
7807
7838
7861
7871
7879
7892
7894
7911
7913
7926
7928
7931
7943
7972
7974
7987
7994
7997
8006
8008
8026
8027
8030
8048
8065
8079
8082
8096
8097
8102
8103
8113
8122
8132
8134
8136
8147
8151
8154
8155
8163
8169
8201
8202
8206
8212
8216
8218
8249
8258
8265
8270
8291
8306
8309
8310
8322
8347
8364
8382
8385
8392
8411
8413
8416
8418
8424
8438
8452
8486
8493
8495
8527
8537
8540
8548
8552
8559
8560
8562
8574
8577
8586
8589
8592
8600
8604
8613
8614
8618
8624
8640
8649
8652
8656
8664
8678
8679
8687
8710
8725
8759
8772
8775
8776
8784
8791
8801
8819
8820
8824
8831
8836
8847
8856
8860
8864
8868
8873
8960
8965
8970
8971
8977
8989
8994
9000
9001
9004
9032
9036
9044
9047
9053
9070
9075
9077
9088
9090
9098
9099
9105
9108
9118
9127
9130
9135
9146
9150
9168
9173
9175
9177
9183
9196
9197
9198
9202
9222
9238
9241
9244
9260
9263
9269
9285
9299
9300
9307
9318
9363
9373
9385
9389
9403
9404
9416
9420
9421
9434
9445
9448
9454
9461
9472
9498
9508
9520
9525
9538
9548
9561
9563
9566
9569
9580
9585
9596
9598
9635
9645
9652
9661
9664
9677
9682
9685
9709
9720
9722
9733
9748
9749
9752
9770
9797
9833
9848
9852
9872
9875
9886
9889
9896
9933
9938
9944
9952
9959
9966
9971
9978
9985
9993
10003
10005
10011
10034
10053
10060
10078
10088
10093
10107
10114
10136
10141
10172
10203
10204
10211
10212
10229
10232
10246
10270
10273
10275
10297
10305
10338
10361
10373
10381
10406
10411
10412
10428
10435
10462
10469
10486
10515
10517
10524
10529
10539
10552
10555
10574
10619
10632
10633
10642
10650
10664
10675
10705
10714
10715
10733
10734
10782
10784
10797
10809
10813
10815
10816
10824
10829
10832
10839
10851
10856
10869
10873
10876
10877
10901
10902
10903
10906
10912
10916
10917
10922
10935
10948
10950
10955
10967
10972
11018
11019
11025
11026
11033
11043
11056
11057
11060
11068
11077
11094
11098
11111
11115
11120
11121
11122
11130
11134
11138
11152
11160
11169
11180
11185
11213
11221
11225
11230
11231
11252
11260
11284
11285
11298
11300
11304
11322
11347
11353
11368
11398
11403
11408
11435
11437
11438
11455
11459
11464
11472
11478
11483
11491
11493
11503
11504
11526
11529
11530
11532
11535
11539
11554
11565
11576
11589
11598
11611
11612
11616
11628
11639
11644
11645
11656
11663
11669
11670
11688
11700
11711
11721
11736
11765
11768
11773
11791
11812
11816
11822
11829
11834
11863
11875
11877
11878
11894
11900
11907
11913
11914
11923
11925
11948
11953
11958
11963
11965
11977
11979
11992
12001
12002
12004
12008
12022
12027
12056
12061
12065
12081
12104
12113
12156
12162
12167
12185
12204
12213
12215
12220
12229
12230
12236
12260
12262
12269
12278
12307
12312
12325
12328
12329
12337
12339
12344
12345
12347
12359
12366
12367
12377
12378
12388
12391
12401
12423
12428
12434
12436
12441
12444
12451
12454
12456
12461
12468
12485
12488
12532
12533
12534
12540
12551
12555
12559
12604
12612
12623
12628
12675
12685
12697
12701
12708
12740
12762
12765
12770
12801
12809
12810
12811
12814
12815
12829
12835
12836
12842
12852
12855
12864
12877
12885
12888
12894
12895
12898
12916
12918
12920
12942
12948
12950
12968
13005
13010
13012
13028
13046
13086
13090
13106
13118
13124
13148
13165
13172
13178
13180
13208
13240
13294
13299
13301
13306
13333
13352
13364
13367
13369
13380
13384
13387
13396
13404
13405
13419
13421
13426
13430
13456
13466
13469
13472
13485
13488
13491
13498
13500
13515
13531
13545
13551
13555
13588
13594
13598
13607
13609
13612
13622
13627
13630
13654
13664
13672
13677
13686
13687
13743
13744
13747
13762
13771
13773
13775
13781
13795
13808
13811
13842
13852
13860
13869
13874
13892
13915
13923
13939
13942
13943
13956
13966
13968
13971
13982
13996
14004
14013
14051
14053
14054
14067
14073
14088
14094
14104
14106
14113
14117
14123
14134
14153
14159
14161
14167
14188
14201
14204
14211
14212
14214
14220
14223
14249
14258
14259
14266
14268
14271
14273
14275
14278
14280
14290
14300
14305
14309
14333
14341
14343
14347
14370
14371
14376
14386
14388
14402
14416
14428
14451
14460
14476
14494
14529
14532
14534
14539
14555
14558
14565
14567
14568
14571
14577
14582
14589
14622
14625
14628
14629
14642
14659
14676
14681
14695
14696
14711
14718
14732
14737
14738
14742
14786
14787
14791
14799
14810
14828
14830
14837
14838
14860
14862
14868
14870
14875
14876
14880
14882
14897
14898
14961
14963
14969
14986
14987
14996
15011
15025
15026
15030

15051
15058
15081
15085
15099
15110
15112
15113
15118
15127
15136
15149
15151
15163
15195
15228
15241
15245
15253
15272
15284
15287
15288
15299
15304
15313
15340
15350
15358
15359
15364
15382
15386
15390
15404
15409
15420
15438
15442
15443
15445
15464
15474
15508
15511
15521
15525
15527
15553
15568
15569
15573
15574
15579
15581
15588
15590
15594
15605
15611
15645
15662
15690
15697
15701
15702
15725
15735
15744
15755
15780
15808
15818
15824
15826
15833
15853
15859
15868
15871
15883
15892
15897
15915
15937
15948
15973
15981
15986
15992
16002
16006
16007
16008
16011
16027
16039
16044
16045
16048
16053
16055
16056
16059
16062
16067
16083
16090
16094
16109
16115
16117
16126
16130
16142
16164
16175
16186
16196
16226
16252
16256
16263
16267
16273
16289
16292
16295
16303
16318
16326
16345
16348
16352
16359
16364
16393
16425
16432
16446
16452
16490
16494
16512
16529
16537
16546
16557
16572
16580
16587
16601
16617
16638
16646
16669
16671
16676
16684
16686
16688
16706
16715
16731
16772
16784
16791
16806
16808
16812
16847
16865
16875
16890
16891
16895
16929
16933
16944
16952
16963
16997
16999
17000
17013
17014
17025
17027
17028
17029
17033
17052
17065
17077
17087
17088
17089
17096
17104
17113
17124
17125
17140
17146
17156
17161
17164
17170
17183
17193
17201
17213
17226
17244
17259
17269
17291
17293
17295
17298
17299
17300
17327
17338
17350
17354
17360
17361
17365
17387
17407
17408
17433
17473
17476
17480
17483
17518
17553
17568
17575
17584
17594
17597
17612
17614
17620
17632
17635
17639
17656
17663
17667
17668
17672
17678
17687
17695
17716
17717
17718
17722
17724
17733
17751
17773
17778
17790
17794
17796
17813
17817
17819
17825
17832
17838
17843
17846
17855
17856
17874
17877
17886
17890
17903
17909
17915
17925
17926
17928
17932
17937
17947
17972
17986
18023
18029
18032
18059
18060
18099
18100
18110
18121
18129
18134
18135
18137
18143
18145
18157
18164
18165
18193
18195
18200
18215
18216
18237
18238
18243
18261
18263
18282
18300
18310
18342
18344
18348
18349
18353
18360
18361
18363
18369
18395
18419
18443
18471
18495
18502
18521
18541
18559
18562
18567
18589
18592
18599
18603
18621
18645
18646
18649
18660
18720
18726
18754
18763
18765
18767
18780
18790
18807
18809
18833
18846
18852
18853
18854
18877
18898
18899
18921
18956
18973
18982
18993
19004
19018
19019
19027
19028
19034
19061
19074
19087
19092
19095
19105
19110
19151
19157
19159
19167
19187
19201
19223
19230
19242
19248
19257
19262
19267
19273
19280
19281
19283
19299
19301
19319
19339
19363
19390
19407
19419
19430
19441
19442
19446
19461
19474
19478
19486
19505
19509
19514
19518
19538
19554
19568
19571
19574
19575
19592
19595
19599
19602
19616
19621
19623
19631
19647
19662
19667
19670
19676
19681
19683
19688
19693
19707
19709
19717
19725
19735
19749
19758
19764
19788
19794
19808
19811
19818
19825
19834
19835
19850
19856
19865
19871
19873
19880
19881
19888
19889
19911
19928
19932
19937
19940
19957
19962
19991
20001
20003
20016
20017
20022
20039
20046
20063
20085
20104
20105
20110
20115
20122
20124
20132
20171
20177
20190
20206
20210
20215
20217
20225
20240
20246
20264
20291
20294
20308
20314
20342
20345
20346
20350
20372
20382
20385
20395
20402
20419
20422
20434
20455
20463
20464
20471
20494
20500
20508
20543
20549
20557
20577
20578
20597
20601
20611
20626
20638
20654
20658
20672
20686
20690
20693
20706
20712
20716
20720
20728
20732
20755
20777
20780
20788
20789
20799
20800
20802
20817
20836
20842
20850
20866
20868
20869
20880
20888
20890
20900
20903
20906
20914
20921
20941
20942
20960
20986
21011
21014
21017
21020
21021
21023
21030
21037
21048
21061
21077
21078
21091
21098
21101
21105
21113
21143
21152
21158
21165
21176
21185
21189
21191
21198
21204
21210
21232
21236
21239
21244
21271
21300
21305
21314
21323
21335
21351
21357
21358
21360
21362
21365
21367
21382
21413
21438
21443
21444
21451
21467
21479
21491
21503
21509
21514
21517
21519
21533
21535
21537
21541
21558
21562
21575
21580
21615
21618
21622
21632
21634
21644
21662
21663
21684
21697
21704
21713
21723
21727
21731
21733
21813
21816
21817
21825
21842
21859
21863
21865
21881
21889
21899
21901
21905
21919
21921
21922
21923
21932
21933
21934
21947
21957
21958
21964
21965
21975
21982
22002
22008
22020
22026
22035
22052
22061
22092
22131
22141
22156
22166
22175
22181
22189
22190
22194
22201
22209
22213
22250
22255
22263
22282
22294
22295
22301
22336
22347
22362
22371
22386
22392
22393
22394
22397
22405
22418
22421
22440
22445
22455
22470
22474
22504
22509
22510
22518
22524
22540
22553
22566
22585
22586
22589
22613
22616
22618
22627
22628
22636
22639
22647
22648
22655
22656
22659
22663
22665
22674
22675
22682
22690
22691
22692
22697
22702
22704
22720
22721
22731
22738
22805
22813
22817
22825
22835
22846
22857
22863
22867
22868
22869
22872
22879
22888
22896
22901
22902
22904
22919
22941
22968
22970
22984
22987
23016
23035
23047
23052
23058
23059
23070
23077
23082
23087
23106
23132
23135
23149
23160
23164
23166
23178
23181
23204
23206
23207
23229
23237
23239
23252
23255
23259
23265
23272
23274
23286
23305
23315
23318
23323
23327
23335
23360
23373
23394
23398
23406
23407
23418
23423
23443
23461
23464
23477
23480
23506
23511
23513
23516
23519
23522
23546
23551
23559
23561
23563
23580
23584
23590
23594
23608
23616
23622
23626
23627
23630
23635
23642
23646
23649
23667
23683
23690
23693
23697
23718
23723
23726
23734
23758
23766
23770
23781
23788
23796
23802
23811
23828
23829
23842
23846
23848
23856
23874
23877
23879
23885
23912
23916
23951
23956
23963
23969
23979
23987
23991
24002
24009
24015
24021
24029
24048
24060
24061
24074
24077
24099
24104
24111
24126
24130
24137
24140
24144
24148
24178
24188
24194
24214
24246
24252
24254
24266
24270
24271
24279
24284
24291
24294
24316
24330
24356
24357
24366
24369
24376
24392
24398
24404
24443
24463
24466
24478
24481
24492
24520
24527
24544
24546
24556
24559
24562
24573
24581
24593
24597
24601
24602
24611
24656
24659
24665
24666
24672
24677
24678
24679
24703
24710
24714
24721
24723
24770
24773
24783
24784
24785
24789
24790
24793
24797
24806
24816
24876
24881
24890
24908
24927
24943
24947
24953
24963
24964
24973
24990
25000
25001
25005
25017
25020
25023
25039
25050
25055
25057
25103
25110
25120
25123
25150
25158
25171
25185
25192
25201
25207
25212
25226
25257
25268
25286
25298
25303
25306
25314
25343
25346
25348
25352
25359
25367
25375
25377
25416
25425
25435
25437
25440
25443
25476
25500
25537
25541
25545
25547
25548
25555
25578
25589
25595
25604
25608
25618
25624
25627
25635
25636
25650
25666
25673
25678
25688
25691
25693
25713
25717
25723
25727
25735
25742
25749
25756
25763
25764
25769
25784
25793
25796
25800
25804
25813
25856
25870
25886
25887
25892
25893
25903
25914
25925
25956
25961
25975
25980
25998
26001
26006
26017
26049
26059
26064
26067
26068
26082
26086
26089
26099
26106
26110
26115
26131
26182
26198
26204
26214
26224
26230
26235
26244
26255
26268
26287
26299
26307
26311
26314
26323
26331
26335
26339
26347
26353
26374
26392
26402
26408
26410
26423
26424
26431
26435
26448
26458
26470
26475
26490
26512
26516
26523
26536
26551
26556
26560
26578
26584
26592
26597
26598
26613
26618
26633
26634
26644
26652
26656
26667
26696
26699
26703
26705
26713
26715
26716
26730
26732
26739
26748
26750
26751
26756
26851
26862
26865
26881
26894
26902
26912
26918
26927
26930
26945
26949
26957
26961
26963
26998
27000
27002
27008
27015
27016
27023
27024
27030
27035
27036
27038
27039
27047
27077
27085
27090
27114
27117
27122
27139
27145
27150
27154
27156
27162
27167
27177
27180
27181
27186
27221
27224
27234
27247
27259
27264
27273
27288
27289
27300
27314
27319
27327
27330
27374
27376
27399
27402
27428
27434
27436
27442
27456
27457
27462
27464
27484
27487
27488
27490
27494
27500
27501
27506
27526
27531
27542
27568
27576
27591
27592
27627
27638
27662
27666
27668
27678
27680
27705
27715
27720
27725
27747
27756
27764
27768
27770
27771
27778
27780
27795
27800
27807
27822
27830
27835
27875
27958
27969
27981
27982
27985
27990
28003
28006
28023
28027
28028
28032
28033
28040
28043
28050
28064
28075
28124
28127
28136
28151
28161
28168
28170
28178
28182
28194
28200
28214
28215
28243
28250
28251
28259
28281
28284
28289
28291
28295
28302
28305
28321
28341
28344
28387
28389
28391
28403
28408
28409
28439
28450
28451
28453
28457
28465
28466
28483
28495
28509
28520
28528
28533
28537
28541
28545
28548
28560
28580
28590
28593
28594

28596
28613
28614
28615
28616
28639
28652
28660
28672
28689
28697
28700
28738
28741
28755
28766
28776
28779
28781
28782
28795
28808
28820
28828
28839
28842
28843
28845
28865
28867
28870
28875
28882
28889
28891
28894
28913
28914
28922
28937
28947
28952
29029
29030
29031
29036
29040
29043
29048
29072
29078
29085
29087
29091
29099
29103
29108
29115
29135
29138
29152
29157
29176
29178
29180
29209
29214
29221
29228
29246
29248
29250
29256
29271
29302
29303
29317
29321
29339
29347
29363
29373
29383
29396
29411
29415
29425
29427
29431
29432
29435
29441
29452
29455
29459
29469
29486
29488
29493
29531
29532
29537
29542
29546
29555
29556
29595
29603
29611
29612
29616
29622
29628
29632
29640
29643
29655
29658
29666
29672
29676
29682
29684
29688
29694
29697
29698
29717
29747
29751
29756
29761
29772
29774
29775
29786
29787
29795
29799
29800
29802
29828
29875
29902
29903
29904
29905
29910
29913
29923
29926
29930
29932
29934
29941
29944
29947
29957
29959
29963
29965
29972
29986
30005
30017
30025
30030
30031
30050
30052
30063
30070
30075
30080
30090
30095
30096
30115
30123
30130
30131
30148
30163
30176
30196
30202
30227
30229
30242
30247
30264
30266
30272
30284
30292
30294
30303
30313
30315
30323
30325
30353
30381
30387
30389
30393
30413
30442
30444
30452
30455
30463
30468
30470
30499
30507
30551
30585
30590
30597
30598
30606
30607
30608
30618
30622
30627
30640
30642
30645
30652
30653
30659
30660
30678
30683
30695
30707
30709
30718
30721
30724
30738
30755
30756
30760
30761
30763
30777
30779
30788
30791
30798
30813
30818
30819
30820
30822
30855
30862
30871
30873
30876
30919
30934
30950
30957
30959
30984
30985
30999
31009
31013
31017
31030
31051
31054
31074
31080
31084
31092
31104
31107
31135
31137
31139
31156
31157
31173
31197
31203
31205
31209
31211
31218
31234
31246
31254
31261
31263
31286
31297
31311
31316
31317
31326
31333
31339
31346
31380
31415
31429
31434
31435
31447
31448
31450
31451
31454
31470
31475
31489
31511
31518
31528
31534
31536
31543
31554
31564
31567
31578
31580
31589
31598
31600
31609
31644
31645
31647
31648
31649
31661
31664
31674
31687
31692
31703
31718
31724
31736
31740
31748
31768
31786
31793
31802
31807
31825
31837
31845
31846
31859
31861
31875
31877
31879
31896
31907
31918
31926
31950
31959
31967
31994
31997
31999
32002
32045
32055
32087
32092
32096
32102
32107
32127
32130
32146
32147
32154
32172
32188
32192
32205
32223
32245
32247
32248
32251
32276
32278
32282
32327
32342
32343
32355
32375
32385
32389
32399
32400
32413
32422
32458
32462
32484
32487
32499
32505
32506
32522
32533
32539
32546
32552
32559
32562
32564
32574
32576
32578
32603
32608
32614
32619
32630
32645
32656
32664
32680
32686
32709
32712
32748
32750
32752
32771
32783
32793
32810
32827
32830
32835
32841
32854
32861
32863
32881
32884
32888
32899
32912
32913
32929
32935
32938
32959
33002
33013
33025
33040
33047
33054
33057
33066
33068
33087
33100
33112
33149
33168
33174
33182
33187
33196
33199
33203
33212
33216
33221
33227
33261
33262
33267
33273
33289
33290
33293
33294
33301
33320
33321
33324
33334
33336
33343
33353
33356
33357
33367
33399
33406
33455
33470
33475
33488
33494
33505
33521
33539
33544
33559
33560
33563
33564
33573
33583
33588
33595
33596
33599
33603
33607
33617
33645
33648
33657
33666
33673
33698
33705
33709
33717
33731
33733
33739
33744
33750
33751
33756
33757
33763
33768
33774
33776
33778
33779
33781
33782
33810
33812
33825
33833
33845
33863
33875
33877
33878
33879
33880
33888
33894
33906
33919
33922
33939
33940
33943
33958
33965
33969
33982
33983
33984
33989
34002
34003
34004
34024
34030
34040
34073
34081
34089
34090
34102
34110
34119
34126
34128
34136
34150
34161
34162
34174
34180
34207
34236
34242
34252
34277
34287
34315
34318
34331
34352
34357
34381
34382
34398
34403
34417
34433
34435
34448
34453
34459
34462
34468
34471
34502
34528
34532
34539
34548
34554
34570
34572
34583
34593
34601
34613
34626
34637
34642
34648
34672
34678
34679
34681
34698
34710
34714
34722
34729
34744
34767
34796
34806
34831
34834
34835
34842
34846
34847
34870
34879
34889
34891
34904
34906
34914
34930
34944
34945
34946
34961
35009
35010
35020
35028
35031
35039
35041
35046
35048
35076
35082
35083
35084
35092
35096
35135
35165
35178
35188
35209
35212
35227
35234
35238
35239
35241
35256
35257
35258
35266
35271
35278
35307
35356
35373
35382
35387
35391
35397
35404
35412
35455
35461
35475
35483
35490
35491
35498
35502
35509
35519
35540
35547
35555
35558
35571
35573
35574
35585
35591
35624
35630
35642
35653
35656
35658
35668
35681
35705
35716
35721
35734
35739
35740
35742
35749
35753
35755
35765
35768
35769
35778
35796
35799
35817
35822
35825
35832
35843
35870
35883
35889
35891
35894
35895
35898
35920
35926
35928
35986
35989
35994
35995
36004
36009
36013
36016
36017
36019
36032
36036
36038
36055
36056
36070
36076
36083
36110
36114
36115
36123
36128
36130
36136
36165
36171
36172
36175
36177
36188
36201
36208
36216
36251
36252
36266
36287
36310
36320
36322
36323
36328
36333
36335
36342
36352
36361
36369
36388
36391
36403
36408
36421
36433
36438
36448
36449
36457
36464
36476
36477
36486
36494
36497
36499
36501
36505
36509
36521
36533
36534
36535
36561
36563
36571
36573
36581
36586
36594
36600
36624
36626
36627
36633
36635
36641
36651
36661
36662
36665
36669
36671
36672
36683
36691
36697
36710
36715
36724
36730
36739
36762
36779
36784
36807
36820
36833
36842
36857
36867
36873
36882
36885
36908
36909
36922
36925
36951
36970
36972
36982
37020
37061
37064
37084
37113
37143
37144
37154
37155
37162
37164
37176
37203
37215
37220
37224
37232
37241
37246
37247
37257
37264
37265
37300
37306
37343
37348
37370
37386
37394
37413
37420
37425
37438
37440
37448
37453
37466
37498
37499
37501
37502
37513
37514
37520
37526
37531
37534
37538
37540
37541
37542
37558
37563
37576
37590
37595
37608
37611
37624
37630
37634
37639
37643
37654
37656
37660
37682
37687
37718
37721
37723
37760
37763
37780
37783
37785
37791
37794
37810
37830
37839
37848
37855
37874
37876
37877
37887
37888
37889
37890
37891
37898
37903
37904
37905
37934
37945
37964
37978
37981
37982
37996
37999
38001
38015
38027
38051
38057
38062
38080
38085
38087
38115
38126
38130
38146
38148
38165
38166
38171
38180
38182
38185
38190
38196
38209
38214
38221
38224
38229
38232
38238
38241
38247
38274
38281
38292
38305
38308
38310
38316
38341
38344
38351
38362
38365
38367
38381
38394
38396
38408
38409
38417
38420
38421
38424
38425
38438
38439
38467
38485
38487
38488
38525
38536
38564
38575
38584
38599
38600
38611
38612
38615
38635
38648
38655
38656
38667
38672
38698
38703
38707
38716
38722
38732
38739
38740
38754
38766
38787
38802
38803
38821
38856
38911
38920
38922
38938
38944
38946
38960
38984
38987
39004
39006
39009
39016
39026
39040
39044
39053
39054
39063
39076
39093
39098
39105
39117
39122
39124
39146
39151
39163
39168
39175
39189
39195
39202
39234
39248
39255
39264
39275
39278
39282
39288
39300
39305
39316
39323
39331
39343
39346
39349
39355
39362
39375
39403
39404
39435
39449
39453
39454
39457
39461
39472
39502
39504
39511
39520
39522
39538
39539
39576
39584
39592
39600
39604
39605
39610
39614
39621
39647
39656
39663
39674
39681
39685
39695
39710
39714
39717
39737
39741
39751
39757
39766
39770
39779
39791
39808
39812
39817
39836
39842
39843
39844
39845
39846
39867
39868
39881
39895
39899
39901
39923
39946
39951
39957
39960
39962
39964
39997
40000
40004
40007
40016
40023
40047
40059
40063
40065
40070
40081
40107
40112
40115
40120
40125
40144
40152
40171
40174
40178
40183
40198
40200
40243
40247
40266
40281
40285
40292
40295
40313
40322
40336
40342
40356
40359
40361
40371
40372
40385
40390
40397
40410
40425
40447
40453
40456
40465
40495
40498
40500
40501
40506
40511
40515
40549
40550
40551
40562
40567
40569
40571
40584
40604
40609
40619
40628
40629
40630
40633
40635
40665
40678
40705
40713
40715
40716
40730
40732
40741
40746
40757
40762
40777
40789
40801
40805
40806
40844
40899
40902
40903
40918
40919
40934
40954
40961
40962
40963
40975
41011
41018
41022
41027
41030
41074
41088
41094
41095
41104
41112
41122
41129
41135
41142
41150
41160
41162
41165
41181
41184
41200
41211
41212
41215
41231
41239
41243
41284
41285
41301
41319
41327
41331
41335
41358
41360
41376
41378
41391
41394
41404
41406
41412
41415
41417
41451
41452
41473
41478
41487
41489
41505
41507
41515
41532
41535
41553
41566
41578
41579
41592
41594
41596
41599
41600
41621
41623
41632
41637

41675
41677
41685
41688
41689
41697
41713
41714
41717
41719
41726
41767
41780
41799
41803
41804
41807
41808
41811
41817
41822
41830
41832
41838
41845
41850
41852
41853
41855
41857
41893
41896
41901
41904
41922
41938
41943
41946
41950
41960
41963
41964
41970
41980
41986
41996
42012
42018
42030
42036
42039
42045
42047
42062
42072
42083
42095
42102
42103
42111
42116
42124
42125
42137
42144
42150
42167
42175
42183
42186
42192
42197
42199
42209
42230
42231
42234
42241
42242
42243
42257
42271
42272
42291
42300
42305
42315
42357
42359
42379
42380
42394
42416
42421
42424
42426
42447
42450
42451
42456
42473
42499
42503
42519
42528
42531
42532
42534
42543
42566
42592
42595
42597
42599
42600
42605
42606
42616
42624
42632
42639
42647
42649
42669
42671
42678
42682
42685
42696
42708
42732
42733
42734
42740
42741
42747
42764
42772
42777
42778
42792
42797
42805
42806
42808
42828
42846
42848
42869
42874
42885
42895
42896
42903
42908
42913
42917
42940
42942
42945
42948
42951
42985
43001
43026
43029
43038
43050
43063
43076
43078
43082
43085
43087
43098
43101
43112
43124
43125
43132
43151
43152
43153
43177
43218
43244
43251
43254
43261
43281
43286
43291
43292
43295
43296
43303
43307
43328
43332
43337
43340
43342
43354
43358
43360
43372
43373
43387
43396
43398
43407
43414
43431
43437
43442
43453
43455
43459
43461
43462
43470
43483
43489
43507
43518
43526
43529
43543
43551
43557
43564
43566
43575
43576
43580
43592
43603
43613
43625
43634
43643
43679
43690
43699
43713
43724
43739
43749
43753
43754
43766
43768
43769
43775
43788
43816
43823
43827
43831
43847
43861
43870
43873
43879
43891
43895
43897
43933
43941
43945
43949
43961
43981
43988
44026
44030
44031
44041
44050
44053
44055
44064
44069
44076
44085
44086
44092
44093
44099
44107
44112
44119
44125
44126
44127
44128
44135
44136
44141
44154
44167
44169
44176
44190
44201
44214
44231
44243
44249
44263
44272
44275
44276
44281
44285
44300
44302
44304
44311
44320
44326
44335
44345
44346
44348
44361
44363
44365
44378
44396
44400
44402
44405
44406
44428
44451
44493
44500
44507
44517
44524
44532
44546
44557
44566
44572
44574
44580
44586
44593
44604
44614
44616
44618
44624
44631
44635
44643
44649
44650
44656
44675
44697
44708
44730
44740
44751
44763
44772
44774
44789
44792
44796
44800
44809
44810
44814
44821
44823
44826
44835
44837
44839
44840
44855
44860
44862
44877
44879
44889
44890
44893
44896
44905
44931
44937
44938
44942
44953
44957
44958
44962
44966
44977
45010
45016
45030
45038
45061
45062
45063
45064
45080
45097
45099
45104
45129
45130
45142
45149
45151
45155
45161
45162
45172
45173
45177
45187
45213
45221
45222
45225
45242
45244
45247
45252
45257
45299
45310
45324
45329
45343
45350
45357
45366
45369
45378
45379
45392
45394
45409
45424
45425
45428
45429
45438
45445
45448
45458
45484
45495
45497
45508
45518
45526
45528
45532
45534
45542
45551
45553
45569
45592
45596
45608
45619
45621
45626
45630
45644
45645
45652
45660
45664
45666
45672
45686
45693
45725
45732
45735
45743
45749
45761
45762
45763
45768
45797
45802
45807
45827
45835
45840
45844
45874
45875
45878
45889
45895
45898
45899
45901
45911
45914
45919
45922
45925
45933
45935
45943
45946
45950
45951
45955
45960
45961
45963
46004
46007
46014
46016
46018
46027
46037
46039
46044
46045
46048
46050
46075
46076
46081
46115
46129
46131
46141
46147
46150
46159
46164
46167
46168
46171
46173
46189
46195
46206
46210
46220
46223
46225
46247
46251
46263
46266
46288
46292
46300
46303
46319
46320
46326
46327
46336
46348
46361
46386
46391
46397
46418
46419
46423
46436
46437
46443
46453
46466
46468
46477
46489
46496
46508
46526
46547
46551
46577
46581
46582
46585
46588
46595
46605
46641
46644
46646
46659
46665
46666
46667
46668
46675
46676
46681
46682
46683
46684
46699
46702
46709
46717
46721
46729
46731
46740
46744
46746
46755
46760
46776
46777
46791
46794
46805
46806
46807
46813
46814
46815
46829
46832
46851
46863
46864
46868
46869
46875
46888
46896
46901
46902
46906
46917
46920
46922
46923
46927
46937
46946
46961
46964
46966
46967
46969
46970
46973
46980
46991
47002
47009
47023
47024
47029
47041
47042
47059
47060
47066
47068
47072
47079
47091
47096
47100
47110
47111
47117
47119
47129
47144
47150
47164
47173
47185
47196
47205
47221
47242
47245
47265
47270
47275
47282
47283
47305
47328
47329
47336
47342
47351
47352
47356
47359
47366
47367
47375
47384
47385
47406
47407
47418
47427
47428
47430
47435
47438
47440
47443
47448
47450
47466
47467
47474
47476
47485
47487
47491
47492
47504
47510
47512
47524
47529
47531
47533
47545
47548
47551
47558
47566
47567
47571
47578
47581
47595
47605
47606
47611
47612
47613
47625
47650
47651
47663
47673
47675
47694
47705
47714
47716
47717
47721
47722
47729
47736
47741
47747
47748
47752
47770
47780
47784
47787
47792
47794
47795
47799
47808
47812
47813
47816
47822
47823
47838
47853
47866
47868
47871
47877
47886
47887
47899
47919
47921
47926
47942
47943
47945
47960
47967
47976
47989
48007
48018
48023
48030
48032
48054
48059
48065
48069
48072
48078
48097
48104
48112
48114
48118
48119
48120
48127
48136
48138
48151
48156
48159
48161
48163
48169
48190
48193
48199
48200
48205
48206
48211
48215
48217
48218
48231
48245
48252
48253
48254
48255
48256
48283
48285
48286
48304
48306
48326
48344
48350
48364
48370
48382
48386
48394
48396
48404
48408
48438
48447
48469
48476
48482
48489
48501
48506
48525
48529
48531
48539
48563
48568
48581
48589
48618
48634
48640
48641
48644
48669
48684
48687
48708
48725
48730
48734
48738
48741
48744
48766
48767
48786
48787
48803
48807
48809
48824
48831
48834
48837
48839
48841
48844
48846
48847
48849
48858
48861
48864
48865
48877
48893
48897
48907
48911
48922
48925
48928
48934
48966
48975
48978
48984
48994
48998
49001
49007
49010
49023
49030
49035
49037
49039
49042
49046
49063
49068
49074
49089
49099
49123
49126
49127
49132
49137
49138
49150
49151
49152
49159
49164
49170
49173
49177
49178
49186
49211
49214
49229
49239
49248
49252
49258
49259
49260
49307
49316
49324
49328
49338
49351
49377
49385
49388
49399
49411
49417
49422
49424
49433
49434
49442
49443
49447
49464
49470
49472
49484
49485
49489
49502
49503
49512
49519
49524
49539
49540
49550
49551
49553
49559
49568
49573
49580
49588
49604
49620
49627
49628
49633
49639
49640
49651
49660
49661
49664
49672
49677
49685
49695
49698
49712
49715
49727
49729
49733
49734
49737
49745
49759
49791
49803
49820
49826
49827
49834
49840
49842
49849
49859
49863
49867
49870
49872
49883
49888
49896
49900
49903
49906
49909
49920
49927
49942
49943
49947
49951
49954
49964
49966
49969
49975
49978
49986
49998
50018
50023
50024
50031
50035
50045
50046
50047
50053
50065
50066
50079
50083
50085
50086
50091
50120
50123
50126
50138
50140
50147
50150
50153
50160
50163
50171
50177
50179
50180
50184
50195
50196
50199
50202
50211
50215
50231
50248
50278
50295
50299
50300
50304
50317
50330
50337
50339
50364
50365
50371
50374
50377
50378
50380
50384
50385
50400
50423
50428
50432
50433
50434
50438
50446
50449
50456
50479
50490
50491
50501
50503
50507
50510
50514
50519
50522
50526
50530
50534
50542
50544
50551
50588
50590
50591
50592
50595
50596
50597
50602
50622
50623
50628
50638
50642
50654
50663
50665
50672
50674
50683
50694
50697
50712
50713
50720
50728
50735
50748
50752
50767
50782
50787
50804
50821
50825
50829
50834
50835
50850
50852
50859
50864
50868
50879
50883
50884
50902
50918
50926
50929
50930
50948
50954
50975
50984
50996
51016
51017
51018
51019
51024
51028
51048
51074
51081
51087
51089
51095
51111
51114
51122
51148
51158
51159
51167
51169
51178
51184
51188
51213
51229
51242
51248
51252
51261
51269
51301
51305
51313
51314
51315
51326
51351
51357
51366
51379
51385
51387
51396
51397
51399
51402
51419
51432
51442
51449
51463
51475
51482
51493
51495
51496
51509
51517
51525
51528
51540
51542
51555
51599
51605
51606
51607
51615
51617
51627
51632
51637
51638
51640
51646
51648
51660
51661
51663
51690
51695
51696
51711
51736
51745
51752
51753
51767
51769
51770
51779
51803
51806
51810
51814
51816
51819
51824
51827
51830
51834
51838
51839
51846
51859
51867
51870
51871
51876
51877
51892
51894
51897
51906
51927
51928
51931
51934
51941
51950
51952
51961
51975
51980
51996
52010
52015
52020
52024
52049
52051
52058
52061
52066
52068
52069
52102
52113
52120
52121
52132
52141
52142
52144
52154
52155
52173
52181
52193
52207
52212
52218
52235
52238
52249
52250
52255
52266
52267
52271
52311
52328
52339
52342
52355
52368
52369
52375
52383
52386
52393
52406
52409
52413
52420
52426
52428
52434
52435
52440
52448
52453
52473
52474
52475
52477
52510

52521
52524
52526
52529
52537
52544
52546
52554
52560
52566
52573
52578
52588
52597
52608
52621
52623
52628
52641
52642
52655
52667
52679
52681
52683
52686
52687
52698
52709
52712
52713
52716
52720
52729
52731
52736
52739
52749
52751
52762
52765
52773
52774
52781
52782
52783
52786
52790
52792
52802
52827
52831
52836
52843
52852
52855
52859
52860
52863
52868
52872
52873
52882
52883
52888
52897
52914
52919
52921
52927
52932
52936
52942
52945
52950
52951
52957
52977
52978
52984
52987
52992
52999
53005
53007
53009
53011
53019
53021
53024
53030
53032
53035
53041
53050
53054
53058
53079
53091
53097
53106
53108
53117
53129
53133
53141
53142
53159
53161
53166
53183
53185
53194
53211
53213
53223
53229
53230
53231
53243
53251
53254
53256
53257
53261
53264
53266
53268
53274
53281
53301
53302
53304
53309
53314
53318
53320

In [61]:
records['sort_record2'] = sort_record2
records['first_record_d'] = first_record_d
records['first_record_diag'] = first_record_diag
records['first_stroke_after_d'] = first_stroke_after_d
records['first_stroke_type'] = first_stroke_type
records['pri'] = pri_record
records['sec'] = sec_record

In [62]:
records['discrepancy'] = records['first_record_d'] < records['yr_birth']

In [63]:
len(first_stroke_after_d)

53323

In [64]:
records[records['discrepancy'] ==True]

Empty DataFrame
Columns: [eid, coded, data_provider, event_dt, read_2, read_3, value1, value2, value3, condition, pri_date_diag, record_diag, 34-0.0, uniq_record_diag, sort_record, yr_birth, sort_record2, first_record_d, first_record_diag, first_stroke_after_d, first_stroke_type, pri, sec, discrepancy]
Index: []

[0 rows x 24 columns]

## Records length

In [65]:
records['noRecords'] = [0 if x == [[np.nan]] else len(x) for x in records['sort_record'] ]
records['noRecords2'] = [0 if x == [[np.nan]] else len(x) for x in records['sort_record2'] ]

In [66]:
records[records['first_stroke_after_d'].isnull() == False]

,eid,coded,data_provider,event_dt,read_2,read_3,value1,value2,value3,condition,...,sort_record2,first_record_d,first_record_diag,first_stroke_after_d,first_stroke_type,pri,sec,discrepancy,noRecords,noRecords2
1,1000421,"[[04/08/2010, cad, sec], [27/05/2010, stroke, ...","[3, 3]","[27/05/2010, 04/10/2010]","[nan, nan]","[XE0VK, XE2uV]","[nan, nan]","[nan, nan]","[nan, nan]","[TIA, CAD]",...,"[[2010-05-27 00:00:00, tia, pri], [2010-05-27 ...",2010-05-27,tia,2010-05-27,stroke,"[[2010-05-27 00:00:00, tia, pri], [2010-10-04 ...","[[2010-05-27 00:00:00, stroke, sec], [2010-08-...",False,4,4
7,1001327,"[[28/03/2016, tia, sec]]","[3, 3]","[29/03/2016, 28/04/2016]","[nan, nan]","[XE0VK, XE0VK]","[nan, nan]","[nan, nan]","[nan, nan]","[TIA, TIA]",...,"[[2016-03-28 00:00:00, tia, sec], [2016-03-29 ...",2016-03-28,tia,2016-03-29,tia,"[[2016-03-29 00:00:00, tia, pri], [2016-04-28 ...","[[2016-03-28 00:00:00, tia, sec]]",False,3,3
15,1002251,"[[27/03/2012, stroke, sec]]","[3, 3, 3]","[05/04/2012, 05/04/2012, 16/09/2013]","[nan, nan, nan]","[G660., X200E, X200E]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]","[Stroke, MI, MI]",...,"[[2012-03-27 00:00:00, stroke, sec], [2012-04-...",2012-03-27,stroke,2012-04-05,stroke,"[[2012-04-05 00:00:00, mi, pri], [2012-04-05 0...","[[2012-03-27 00:00:00, stroke, sec]]",False,4,4
33,1004792,"[[15/12/2003, haemorrhage, sec]]","[3, 3, 3, 3]","[01/11/2003, 07/02/2010, 29/04/2015, 30/04/2015]","[nan, nan, nan, nan]","[XE0VF, G6..., G5731, G5731]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[Stroke, Stroke, Afib, Afib]",...,"[[2003-11-01 00:00:00, stroke, pri], [2003-12-...",2003-11-01,stroke,2010-02-07,stroke,"[[2003-11-01 00:00:00, stroke, pri], [2010-02-...","[[2003-12-15 00:00:00, haemorrhage, sec]]",False,5,5
67,1009048,"[[13/03/2011, stroke, sec]]","[3, 3, 3, 3]","[15/03/2011, 25/03/2011, 25/03/2011, 20/06/2011]","[nan, nan, nan, nan]","[XE0VK, G5730, X00D1, G5730]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[TIA, Afib, Stroke, Afib]",...,"[[2011-03-13 00:00:00, stroke, sec], [2011-03-...",2011-03-13,stroke,2011-03-15,tia,"[[2011-03-15 00:00:00, tia, pri], [2011-03-25 ...","[[2011-03-13 00:00:00, stroke, sec]]",False,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53304,6014234,[],"[3, 3, 3]","[08/10/2007, 20/04/2008, 27/05/2008]","[nan, nan, nan]","[XaINF, Xa00J, XaBEC]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]","[MI, Stroke, Stroke]",...,"[[2007-10-08 00:00:00, mi, pri], [2008-04-20 0...",2007-10-08,mi,2008-04-20,stroke,"[[2007-10-08 00:00:00, mi, pri], [2008-04-20 0...",[],False,3,3
53309,6015854,[],"[3, 3, 3, 3]","[27/11/2004, 27/11/2004, 21/09/2012, 11/12/2012]","[nan, nan, nan, nan]","[G65z., XE0VK, XE0VK, XE0VK]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[TIA, TIA, TIA, TIA]",...,"[[2004-11-27 00:00:00, tia, pri], [2012-09-21 ...",2004-11-27,tia,2012-09-21,tia,"[[2004-11-27 00:00:00, tia, pri], [2012-09-21 ...",[],False,3,3
53314,6019332,[],"[3, 3]","[01/03/2000, 18/03/2008]","[nan, nan]","[G668., G668.]","[nan, nan]","[nan, nan]","[nan, nan]","[Stroke, Stroke]",...,"[[2000-03-01 00:00:00, stroke, pri], [2008-03-...",2000-03-01,stroke,2008-03-18,stroke,"[[2000-03-01 00:00:00, stroke, pri], [2008-03-...",[],False,2,2
53318,6020725,[],"[3, 3]","[01/01/1993, 18/09/2003]","[nan, nan]","[G66.., XE0VK]","[nan, nan]","[nan, nan]","[nan, nan]","[Stroke, TIA]",...,"[[1993-01-01 00:00:00, stroke, pri], [2003-09-...",1993-01-01,stroke,2003-09-18,tia,"[[1993-01-01 00:00:00, stroke, pri], [2003-09-...",[],False,2,2
53320,6021143,[],"[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...","[20/01/2005, 11/02/2005, 07/04/2005, 21/11/200...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[X00DW, X00DW, X00DW, X00DW, X00DW, X00DW, X00...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, ...",...,"[[2005-01-20 00:00:00, tia, pri], [2005-02-11 ...",2005-01-20,tia,2005-02-11,tia,"[[2005-01-20 00:00:00, tia, pri], [2005-02-11 ...",[],False,19,19

## interval calculation

In [67]:
records['event_int'] = (records['first_stroke_after_d'] - records['first_record_d'])/np.timedelta64(1, 'M')

## report

In [95]:
records[(records['noRecords'] > 1 ) & (records['event_int'].isnull() == False) & (records['discrepancy'] == False)].eid.count()

5864

In [69]:
records[(records['noRecords'] > 1 ) & (records['event_int'] < 0.233) & (records['discrepancy'] == False)].eid.count()

1702

In [70]:
records[(records['noRecords'] > 1 ) & (records['event_int'] >= 0.233) & (records['event_int'] < 1) & (records['discrepancy'] == False)].eid.count()

643

In [71]:
records[(records['noRecords'] > 1 ) & (records['event_int'] >= 1) & (records['event_int'] < 6) & (records['discrepancy'] == False)].eid.count()

623

In [72]:
records[(records['noRecords'] > 1 ) & (records['event_int'] >= 6) & (records['event_int'] < 12) & (records['discrepancy'] == False)].eid.count()

332

In [73]:
records[(records['noRecords'] > 1 ) & (records['event_int'] >= 12)  & (records['discrepancy'] == False)].eid.count()

2564

In [74]:
records[(records['noRecords'] > 1 ) & (records['discrepancy'] == True)].eid.count()

0

In [75]:
records[(records['noRecords'] > 1 ) & (records['first_stroke_after_d'].isnull() == True)]

,eid,coded,data_provider,event_dt,read_2,read_3,value1,value2,value3,condition,...,first_record_d,first_record_diag,first_stroke_after_d,first_stroke_type,pri,sec,discrepancy,noRecords,noRecords2,event_int
3,1000584,"[[16/06/1997, cad, sec], [19/10/2004, afib, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1997-06-16,cad,NaT,NaN,[],"[[1997-06-16 00:00:00, cad, sec], [2004-10-19 ...",False,2,2,NaN
12,1001874,"[[30/10/2013, mi, sec], [31/10/2013, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2013-10-30,mi,NaT,NaN,[],"[[2013-10-30 00:00:00, mi, sec], [2013-10-31 0...",False,2,2,NaN
14,1001953,"[[10/01/2014, cad, sec], [09/02/2007, afib, se...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2007-02-09,afib,NaT,NaN,[],"[[2007-02-09 00:00:00, afib, sec], [2014-01-10...",False,3,3,NaN
16,1002307,"[[30/04/2000, mi, sec], [21/12/2000, cad, sec]]","[3, 3]","[30/04/2000, 05/05/2000]","[nan, nan]","[XE0Uh, XE2aA]","[nan, nan]","[nan, nan]","[nan, nan]","[MI, MI]",...,2000-04-30,mi,NaT,NaN,"[[2000-04-30 00:00:00, mi, pri], [2000-05-05 0...","[[2000-04-30 00:00:00, mi, sec], [2000-12-21 0...",False,4,4,NaN
17,1002346,"[[20/12/2001, mi, sec], [24/01/2005, cad, sec]]","[3, 3]","[31/12/2001, 22/12/2004]","[nan, nan]","[XE0Uh, XE2uV]","[nan, nan]","[nan, nan]","[nan, nan]","[MI, CAD]",...,2001-12-20,mi,NaT,NaN,"[[2001-12-31 00:00:00, mi, pri], [2004-12-22 0...","[[2001-12-20 00:00:00, mi, sec], [2005-01-24 0...",False,4,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53295,6011268,[],"[3, 3]","[15/10/2014, 23/12/2014]","[nan, nan]","[G5730, Xa2E8]","[nan, nan]","[nan, nan]","[nan, nan]","[Afib, Afib]",...,2014-10-15,afib,NaT,NaN,"[[2014-10-15 00:00:00, afib, pri], [2014-12-23...",[],False,2,2,NaN
53296,6011438,[],"[3, 3]","[27/08/2013, 25/02/2015]","[nan, nan]","[XE2uV, XE2uV]","[nan, nan]","[nan, nan]","[nan, nan]","[CAD, CAD]",...,2013-08-27,cad,NaT,NaN,"[[2013-08-27 00:00:00, cad, pri], [2015-02-25 ...",[],False,2,2,NaN
53299,6013342,[],"[3, 3, 3, 3, 3]","[19/02/2009, 08/10/2009, 27/01/2011, 10/08/201...","[nan, nan, nan, nan, nan]","[XE2uV, XE2uV, XE2uV, XE2uV, XE2uV]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[CAD, CAD, CAD, CAD, CAD]",...,2009-02-19,cad,NaT,NaN,"[[2009-02-19 00:00:00, cad, pri], [2009-10-08 ...",[],False,5,5,NaN
53300,6013397,[],"[3, 3, 3, 3, 3, 3, 3]","[12/03/2005, 12/03/2005, 12/03/2005, 17/12/200...","[nan, nan, nan, nan, nan, nan, nan]","[G5730, G6..., XE0VJ, G5730, G58.., G5730, G5730]","[nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan]","[Afib, Stroke, Stroke, Afib, HF, Afib, Afib]",...,2005-03-12,stroke,NaT,NaN,"[[2005-03-12 00:00:00, stroke, pri], [2005-03-...",[],False,6,6,NaN
53316,6019969,[],"[2, 2, 2, 2, 2, 2, 2, 2, 2]","[17/04/2015, 12/05/2015, 14/05/2015, 19/05/201...","[G5730, G5730, G5730, G5730, G5730, G5730, G57...","[nan, nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan, nan]","[Afib, Afib, Afib, Afib, Afib, Afib, Afib, Afi...",...,2015-04-17,afib,NaT,NaN,"[[2015-04-17 00:00:00, afib, pri], [2015-05-12...",[],False,9,9,NaN

In [76]:
records[(records['noRecords'] > 1) & (records['first_stroke_after_d'].isnull() == True) & (records['discrepancy'] == False)]

,eid,coded,data_provider,event_dt,read_2,read_3,value1,value2,value3,condition,...,first_record_d,first_record_diag,first_stroke_after_d,first_stroke_type,pri,sec,discrepancy,noRecords,noRecords2,event_int
3,1000584,"[[16/06/1997, cad, sec], [19/10/2004, afib, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1997-06-16,cad,NaT,NaN,[],"[[1997-06-16 00:00:00, cad, sec], [2004-10-19 ...",False,2,2,NaN
12,1001874,"[[30/10/2013, mi, sec], [31/10/2013, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2013-10-30,mi,NaT,NaN,[],"[[2013-10-30 00:00:00, mi, sec], [2013-10-31 0...",False,2,2,NaN
14,1001953,"[[10/01/2014, cad, sec], [09/02/2007, afib, se...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2007-02-09,afib,NaT,NaN,[],"[[2007-02-09 00:00:00, afib, sec], [2014-01-10...",False,3,3,NaN
16,1002307,"[[30/04/2000, mi, sec], [21/12/2000, cad, sec]]","[3, 3]","[30/04/2000, 05/05/2000]","[nan, nan]","[XE0Uh, XE2aA]","[nan, nan]","[nan, nan]","[nan, nan]","[MI, MI]",...,2000-04-30,mi,NaT,NaN,"[[2000-04-30 00:00:00, mi, pri], [2000-05-05 0...","[[2000-04-30 00:00:00, mi, sec], [2000-12-21 0...",False,4,4,NaN
17,1002346,"[[20/12/2001, mi, sec], [24/01/2005, cad, sec]]","[3, 3]","[31/12/2001, 22/12/2004]","[nan, nan]","[XE0Uh, XE2uV]","[nan, nan]","[nan, nan]","[nan, nan]","[MI, CAD]",...,2001-12-20,mi,NaT,NaN,"[[2001-12-31 00:00:00, mi, pri], [2004-12-22 0...","[[2001-12-20 00:00:00, mi, sec], [2005-01-24 0...",False,4,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53295,6011268,[],"[3, 3]","[15/10/2014, 23/12/2014]","[nan, nan]","[G5730, Xa2E8]","[nan, nan]","[nan, nan]","[nan, nan]","[Afib, Afib]",...,2014-10-15,afib,NaT,NaN,"[[2014-10-15 00:00:00, afib, pri], [2014-12-23...",[],False,2,2,NaN
53296,6011438,[],"[3, 3]","[27/08/2013, 25/02/2015]","[nan, nan]","[XE2uV, XE2uV]","[nan, nan]","[nan, nan]","[nan, nan]","[CAD, CAD]",...,2013-08-27,cad,NaT,NaN,"[[2013-08-27 00:00:00, cad, pri], [2015-02-25 ...",[],False,2,2,NaN
53299,6013342,[],"[3, 3, 3, 3, 3]","[19/02/2009, 08/10/2009, 27/01/2011, 10/08/201...","[nan, nan, nan, nan, nan]","[XE2uV, XE2uV, XE2uV, XE2uV, XE2uV]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[CAD, CAD, CAD, CAD, CAD]",...,2009-02-19,cad,NaT,NaN,"[[2009-02-19 00:00:00, cad, pri], [2009-10-08 ...",[],False,5,5,NaN
53300,6013397,[],"[3, 3, 3, 3, 3, 3, 3]","[12/03/2005, 12/03/2005, 12/03/2005, 17/12/200...","[nan, nan, nan, nan, nan, nan, nan]","[G5730, G6..., XE0VJ, G5730, G58.., G5730, G5730]","[nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan]","[Afib, Stroke, Stroke, Afib, HF, Afib, Afib]",...,2005-03-12,stroke,NaT,NaN,"[[2005-03-12 00:00:00, stroke, pri], [2005-03-...",[],False,6,6,NaN
53316,6019969,[],"[2, 2, 2, 2, 2, 2, 2, 2, 2]","[17/04/2015, 12/05/2015, 14/05/2015, 19/05/201...","[G5730, G5730, G5730, G5730, G5730, G5730, G57...","[nan, nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan, nan]","[Afib, Afib, Afib, Afib, Afib, Afib, Afib, Afi...",...,2015-04-17,afib,NaT,NaN,"[[2015-04-17 00:00:00, afib, pri], [2015-05-12...",[],False,9,9,NaN

In [77]:
records[records['first_stroke_type'].isnull() == False]

,eid,coded,data_provider,event_dt,read_2,read_3,value1,value2,value3,condition,...,first_record_d,first_record_diag,first_stroke_after_d,first_stroke_type,pri,sec,discrepancy,noRecords,noRecords2,event_int
1,1000421,"[[04/08/2010, cad, sec], [27/05/2010, stroke, ...","[3, 3]","[27/05/2010, 04/10/2010]","[nan, nan]","[XE0VK, XE2uV]","[nan, nan]","[nan, nan]","[nan, nan]","[TIA, CAD]",...,2010-05-27,tia,2010-05-27,stroke,"[[2010-05-27 00:00:00, tia, pri], [2010-10-04 ...","[[2010-05-27 00:00:00, stroke, sec], [2010-08-...",False,4,4,0.000000
7,1001327,"[[28/03/2016, tia, sec]]","[3, 3]","[29/03/2016, 28/04/2016]","[nan, nan]","[XE0VK, XE0VK]","[nan, nan]","[nan, nan]","[nan, nan]","[TIA, TIA]",...,2016-03-28,tia,2016-03-29,tia,"[[2016-03-29 00:00:00, tia, pri], [2016-04-28 ...","[[2016-03-28 00:00:00, tia, sec]]",False,3,3,0.032855
15,1002251,"[[27/03/2012, stroke, sec]]","[3, 3, 3]","[05/04/2012, 05/04/2012, 16/09/2013]","[nan, nan, nan]","[G660., X200E, X200E]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]","[Stroke, MI, MI]",...,2012-03-27,stroke,2012-04-05,stroke,"[[2012-04-05 00:00:00, mi, pri], [2012-04-05 0...","[[2012-03-27 00:00:00, stroke, sec]]",False,4,4,0.295694
33,1004792,"[[15/12/2003, haemorrhage, sec]]","[3, 3, 3, 3]","[01/11/2003, 07/02/2010, 29/04/2015, 30/04/2015]","[nan, nan, nan, nan]","[XE0VF, G6..., G5731, G5731]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[Stroke, Stroke, Afib, Afib]",...,2003-11-01,stroke,2010-02-07,stroke,"[[2003-11-01 00:00:00, stroke, pri], [2010-02-...","[[2003-12-15 00:00:00, haemorrhage, sec]]",False,5,5,75.237685
67,1009048,"[[13/03/2011, stroke, sec]]","[3, 3, 3, 3]","[15/03/2011, 25/03/2011, 25/03/2011, 20/06/2011]","[nan, nan, nan, nan]","[XE0VK, G5730, X00D1, G5730]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[TIA, Afib, Stroke, Afib]",...,2011-03-13,stroke,2011-03-15,tia,"[[2011-03-15 00:00:00, tia, pri], [2011-03-25 ...","[[2011-03-13 00:00:00, stroke, sec]]",False,5,5,0.065710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53304,6014234,[],"[3, 3, 3]","[08/10/2007, 20/04/2008, 27/05/2008]","[nan, nan, nan]","[XaINF, Xa00J, XaBEC]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]","[MI, Stroke, Stroke]",...,2007-10-08,mi,2008-04-20,stroke,"[[2007-10-08 00:00:00, mi, pri], [2008-04-20 0...",[],False,3,3,6.406702
53309,6015854,[],"[3, 3, 3, 3]","[27/11/2004, 27/11/2004, 21/09/2012, 11/12/2012]","[nan, nan, nan, nan]","[G65z., XE0VK, XE0VK, XE0VK]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[TIA, TIA, TIA, TIA]",...,2004-11-27,tia,2012-09-21,tia,"[[2004-11-27 00:00:00, tia, pri], [2012-09-21 ...",[],False,3,3,93.800694
53314,6019332,[],"[3, 3]","[01/03/2000, 18/03/2008]","[nan, nan]","[G668., G668.]","[nan, nan]","[nan, nan]","[nan, nan]","[Stroke, Stroke]",...,2000-03-01,stroke,2008-03-18,stroke,"[[2000-03-01 00:00:00, stroke, pri], [2008-03-...",[],False,2,2,96.560504
53318,6020725,[],"[3, 3]","[01/01/1993, 18/09/2003]","[nan, nan]","[G66.., XE0VK]","[nan, nan]","[nan, nan]","[nan, nan]","[Stroke, TIA]",...,1993-01-01,stroke,2003-09-18,tia,"[[1993-01-01 00:00:00, stroke, pri], [2003-09-...",[],False,2,2,128.528307
53320,6021143,[],"[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...","[20/01/2005, 11/02/2005, 07/04/2005, 21/11/200...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[X00DW, X00DW, X00DW, X00DW, X00DW, X00DW, X00...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, ...",...,2005-01-20,tia,2005-02-11,tia,"[[2005-01-20 00:00:00, tia, pri], [2005-02-11 ...",[],False,19,19,0.722807

## Pickle

In [78]:
final_records= records[(records['event_int'] >= 0) &(records['noRecords'] > 1) & (records['first_stroke_after_d'].isnull() == False) & (records['discrepancy'] == False)]

In [79]:
final_records

,eid,coded,data_provider,event_dt,read_2,read_3,value1,value2,value3,condition,...,first_record_d,first_record_diag,first_stroke_after_d,first_stroke_type,pri,sec,discrepancy,noRecords,noRecords2,event_int
1,1000421,"[[04/08/2010, cad, sec], [27/05/2010, stroke, ...","[3, 3]","[27/05/2010, 04/10/2010]","[nan, nan]","[XE0VK, XE2uV]","[nan, nan]","[nan, nan]","[nan, nan]","[TIA, CAD]",...,2010-05-27,tia,2010-05-27,stroke,"[[2010-05-27 00:00:00, tia, pri], [2010-10-04 ...","[[2010-05-27 00:00:00, stroke, sec], [2010-08-...",False,4,4,0.000000
7,1001327,"[[28/03/2016, tia, sec]]","[3, 3]","[29/03/2016, 28/04/2016]","[nan, nan]","[XE0VK, XE0VK]","[nan, nan]","[nan, nan]","[nan, nan]","[TIA, TIA]",...,2016-03-28,tia,2016-03-29,tia,"[[2016-03-29 00:00:00, tia, pri], [2016-04-28 ...","[[2016-03-28 00:00:00, tia, sec]]",False,3,3,0.032855
15,1002251,"[[27/03/2012, stroke, sec]]","[3, 3, 3]","[05/04/2012, 05/04/2012, 16/09/2013]","[nan, nan, nan]","[G660., X200E, X200E]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]","[Stroke, MI, MI]",...,2012-03-27,stroke,2012-04-05,stroke,"[[2012-04-05 00:00:00, mi, pri], [2012-04-05 0...","[[2012-03-27 00:00:00, stroke, sec]]",False,4,4,0.295694
33,1004792,"[[15/12/2003, haemorrhage, sec]]","[3, 3, 3, 3]","[01/11/2003, 07/02/2010, 29/04/2015, 30/04/2015]","[nan, nan, nan, nan]","[XE0VF, G6..., G5731, G5731]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[Stroke, Stroke, Afib, Afib]",...,2003-11-01,stroke,2010-02-07,stroke,"[[2003-11-01 00:00:00, stroke, pri], [2010-02-...","[[2003-12-15 00:00:00, haemorrhage, sec]]",False,5,5,75.237685
67,1009048,"[[13/03/2011, stroke, sec]]","[3, 3, 3, 3]","[15/03/2011, 25/03/2011, 25/03/2011, 20/06/2011]","[nan, nan, nan, nan]","[XE0VK, G5730, X00D1, G5730]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[TIA, Afib, Stroke, Afib]",...,2011-03-13,stroke,2011-03-15,tia,"[[2011-03-15 00:00:00, tia, pri], [2011-03-25 ...","[[2011-03-13 00:00:00, stroke, sec]]",False,5,5,0.065710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53304,6014234,[],"[3, 3, 3]","[08/10/2007, 20/04/2008, 27/05/2008]","[nan, nan, nan]","[XaINF, Xa00J, XaBEC]","[nan, nan, nan]","[nan, nan, nan]","[nan, nan, nan]","[MI, Stroke, Stroke]",...,2007-10-08,mi,2008-04-20,stroke,"[[2007-10-08 00:00:00, mi, pri], [2008-04-20 0...",[],False,3,3,6.406702
53309,6015854,[],"[3, 3, 3, 3]","[27/11/2004, 27/11/2004, 21/09/2012, 11/12/2012]","[nan, nan, nan, nan]","[G65z., XE0VK, XE0VK, XE0VK]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[TIA, TIA, TIA, TIA]",...,2004-11-27,tia,2012-09-21,tia,"[[2004-11-27 00:00:00, tia, pri], [2012-09-21 ...",[],False,3,3,93.800694
53314,6019332,[],"[3, 3]","[01/03/2000, 18/03/2008]","[nan, nan]","[G668., G668.]","[nan, nan]","[nan, nan]","[nan, nan]","[Stroke, Stroke]",...,2000-03-01,stroke,2008-03-18,stroke,"[[2000-03-01 00:00:00, stroke, pri], [2008-03-...",[],False,2,2,96.560504
53318,6020725,[],"[3, 3]","[01/01/1993, 18/09/2003]","[nan, nan]","[G66.., XE0VK]","[nan, nan]","[nan, nan]","[nan, nan]","[Stroke, TIA]",...,1993-01-01,stroke,2003-09-18,tia,"[[1993-01-01 00:00:00, stroke, pri], [2003-09-...",[],False,2,2,128.528307
53320,6021143,[],"[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...","[20/01/2005, 11/02/2005, 07/04/2005, 21/11/200...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[X00DW, X00DW, X00DW, X00DW, X00DW, X00DW, X00...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, ...",...,2005-01-20,tia,2005-02-11,tia,"[[2005-01-20 00:00:00, tia, pri], [2005-02-11 ...",[],False,19,19,0.722807

In [80]:
final_records = final_records[['eid', 'coded', 'uniq_record_diag', 'sort_record2',
                               'first_record_d', 'first_record_diag', 'first_stroke_after_d', 'first_stroke_type',
                               'pri', 'sec', 'yr_birth', 'noRecords', 'discrepancy', 'event_int']]

In [81]:
records.to_pickle('../primary_care/full_records.pkl')

In [82]:
final_records.to_pickle('../primary_care/records.pkl')

In [84]:
records

,eid,coded,data_provider,event_dt,read_2,read_3,value1,value2,value3,condition,...,first_record_d,first_record_diag,first_stroke_after_d,first_stroke_type,pri,sec,discrepancy,noRecords,noRecords2,event_int
0,1000255,"[[02/09/2015, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2015-09-02,cad,NaT,NaN,[],"[[2015-09-02 00:00:00, cad, sec]]",False,1,1,NaN
1,1000421,"[[04/08/2010, cad, sec], [27/05/2010, stroke, ...","[3, 3]","[27/05/2010, 04/10/2010]","[nan, nan]","[XE0VK, XE2uV]","[nan, nan]","[nan, nan]","[nan, nan]","[TIA, CAD]",...,2010-05-27,tia,2010-05-27,stroke,"[[2010-05-27 00:00:00, tia, pri], [2010-10-04 ...","[[2010-05-27 00:00:00, stroke, sec], [2010-08-...",False,4,4,0.000000
2,1000466,"[[11/06/2002, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2002-06-11,cad,NaT,NaN,[],"[[2002-06-11 00:00:00, cad, sec]]",False,1,1,NaN
3,1000584,"[[16/06/1997, cad, sec], [19/10/2004, afib, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1997-06-16,cad,NaT,NaN,[],"[[1997-06-16 00:00:00, cad, sec], [2004-10-19 ...",False,2,2,NaN
4,1000674,"[[31/05/2006, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2006-05-31,cad,NaT,NaN,[],"[[2006-05-31 00:00:00, cad, sec]]",False,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53318,6020725,[],"[3, 3]","[01/01/1993, 18/09/2003]","[nan, nan]","[G66.., XE0VK]","[nan, nan]","[nan, nan]","[nan, nan]","[Stroke, TIA]",...,1993-01-01,stroke,2003-09-18,tia,"[[1993-01-01 00:00:00, stroke, pri], [2003-09-...",[],False,2,2,128.528307
53319,6021009,[],[3],[09/06/2016],[nan],[G5730],[nan],[nan],[nan],[Afib],...,2016-06-09,afib,NaT,NaN,"[[2016-06-09 00:00:00, afib, pri]]",[],False,1,1,NaN
53320,6021143,[],"[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...","[20/01/2005, 11/02/2005, 07/04/2005, 21/11/200...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[X00DW, X00DW, X00DW, X00DW, X00DW, X00DW, X00...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, ...",...,2005-01-20,tia,2005-02-11,tia,"[[2005-01-20 00:00:00, tia, pri], [2005-02-11 ...",[],False,19,19,0.722807
53321,6022795,[],[2],[19/01/2015],[G5730],[nan],[nan],[nan],[nan],[Afib],...,2015-01-19,afib,NaT,NaN,"[[2015-01-19 00:00:00, afib, pri]]",[],False,1,1,NaN
53322,6023090,[],[3],[29/07/2005],[nan],[XE2uV],[nan],[nan],[nan],[CAD],...,2005-07-29,cad,NaT,NaN,"[[2005-07-29 00:00:00, cad, pri]]",[],False,1,1,NaN

In [85]:
records.columns

Index(['eid', 'coded', 'data_provider', 'event_dt', 'read_2', 'read_3',
       'value1', 'value2', 'value3', 'condition', 'pri_date_diag',
       'record_diag', '34-0.0', 'uniq_record_diag', 'sort_record', 'yr_birth',
       'sort_record2', 'first_record_d', 'first_record_diag',
       'first_stroke_after_d', 'first_stroke_type', 'pri', 'sec',
       'discrepancy', 'noRecords', 'noRecords2', 'event_int'],
      dtype='object')

In [94]:
records[records['noRecords'].isnull() == False]

,eid,coded,data_provider,event_dt,read_2,read_3,value1,value2,value3,condition,...,first_record_d,first_record_diag,first_stroke_after_d,first_stroke_type,pri,sec,discrepancy,noRecords,noRecords2,event_int
0,1000255,"[[02/09/2015, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2015-09-02,cad,NaT,NaN,[],"[[2015-09-02 00:00:00, cad, sec]]",False,1,1,NaN
1,1000421,"[[04/08/2010, cad, sec], [27/05/2010, stroke, ...","[3, 3]","[27/05/2010, 04/10/2010]","[nan, nan]","[XE0VK, XE2uV]","[nan, nan]","[nan, nan]","[nan, nan]","[TIA, CAD]",...,2010-05-27,tia,2010-05-27,stroke,"[[2010-05-27 00:00:00, tia, pri], [2010-10-04 ...","[[2010-05-27 00:00:00, stroke, sec], [2010-08-...",False,4,4,0.000000
2,1000466,"[[11/06/2002, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2002-06-11,cad,NaT,NaN,[],"[[2002-06-11 00:00:00, cad, sec]]",False,1,1,NaN
3,1000584,"[[16/06/1997, cad, sec], [19/10/2004, afib, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1997-06-16,cad,NaT,NaN,[],"[[1997-06-16 00:00:00, cad, sec], [2004-10-19 ...",False,2,2,NaN
4,1000674,"[[31/05/2006, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2006-05-31,cad,NaT,NaN,[],"[[2006-05-31 00:00:00, cad, sec]]",False,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53318,6020725,[],"[3, 3]","[01/01/1993, 18/09/2003]","[nan, nan]","[G66.., XE0VK]","[nan, nan]","[nan, nan]","[nan, nan]","[Stroke, TIA]",...,1993-01-01,stroke,2003-09-18,tia,"[[1993-01-01 00:00:00, stroke, pri], [2003-09-...",[],False,2,2,128.528307
53319,6021009,[],[3],[09/06/2016],[nan],[G5730],[nan],[nan],[nan],[Afib],...,2016-06-09,afib,NaT,NaN,"[[2016-06-09 00:00:00, afib, pri]]",[],False,1,1,NaN
53320,6021143,[],"[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...","[20/01/2005, 11/02/2005, 07/04/2005, 21/11/200...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[X00DW, X00DW, X00DW, X00DW, X00DW, X00DW, X00...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, ...",...,2005-01-20,tia,2005-02-11,tia,"[[2005-01-20 00:00:00, tia, pri], [2005-02-11 ...",[],False,19,19,0.722807
53321,6022795,[],[2],[19/01/2015],[G5730],[nan],[nan],[nan],[nan],[Afib],...,2015-01-19,afib,NaT,NaN,"[[2015-01-19 00:00:00, afib, pri]]",[],False,1,1,NaN
53322,6023090,[],[3],[29/07/2005],[nan],[XE2uV],[nan],[nan],[nan],[CAD],...,2005-07-29,cad,NaT,NaN,"[[2005-07-29 00:00:00, cad, pri]]",[],False,1,1,NaN

In [96]:
records[(records['noRecords'] > 1 ) & (records['event_int'].isnull() == False) & (records['discrepancy'] == False)].first_record_diag.value_counts()

stroke         2127
tia            1505
cad             737
afib            676
mi              554
haemorrhage     148
hf              101
precursor        16
Name: first_record_diag, dtype: int64

In [102]:
records[(records['noRecords'] > 1) & (records['discrepancy'] == False)]

,eid,coded,data_provider,event_dt,read_2,read_3,value1,value2,value3,condition,...,first_record_d,first_record_diag,first_stroke_after_d,first_stroke_type,pri,sec,discrepancy,noRecords,noRecords2,event_int
1,1000421,"[[04/08/2010, cad, sec], [27/05/2010, stroke, ...","[3, 3]","[27/05/2010, 04/10/2010]","[nan, nan]","[XE0VK, XE2uV]","[nan, nan]","[nan, nan]","[nan, nan]","[TIA, CAD]",...,2010-05-27,tia,2010-05-27,stroke,"[[2010-05-27 00:00:00, tia, pri], [2010-10-04 ...","[[2010-05-27 00:00:00, stroke, sec], [2010-08-...",False,4,4,0.000000
3,1000584,"[[16/06/1997, cad, sec], [19/10/2004, afib, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1997-06-16,cad,NaT,NaN,[],"[[1997-06-16 00:00:00, cad, sec], [2004-10-19 ...",False,2,2,NaN
7,1001327,"[[28/03/2016, tia, sec]]","[3, 3]","[29/03/2016, 28/04/2016]","[nan, nan]","[XE0VK, XE0VK]","[nan, nan]","[nan, nan]","[nan, nan]","[TIA, TIA]",...,2016-03-28,tia,2016-03-29,tia,"[[2016-03-29 00:00:00, tia, pri], [2016-04-28 ...","[[2016-03-28 00:00:00, tia, sec]]",False,3,3,0.032855
12,1001874,"[[30/10/2013, mi, sec], [31/10/2013, cad, sec]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2013-10-30,mi,NaT,NaN,[],"[[2013-10-30 00:00:00, mi, sec], [2013-10-31 0...",False,2,2,NaN
14,1001953,"[[10/01/2014, cad, sec], [09/02/2007, afib, se...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2007-02-09,afib,NaT,NaN,[],"[[2007-02-09 00:00:00, afib, sec], [2014-01-10...",False,3,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53309,6015854,[],"[3, 3, 3, 3]","[27/11/2004, 27/11/2004, 21/09/2012, 11/12/2012]","[nan, nan, nan, nan]","[G65z., XE0VK, XE0VK, XE0VK]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[TIA, TIA, TIA, TIA]",...,2004-11-27,tia,2012-09-21,tia,"[[2004-11-27 00:00:00, tia, pri], [2012-09-21 ...",[],False,3,3,93.800694
53314,6019332,[],"[3, 3]","[01/03/2000, 18/03/2008]","[nan, nan]","[G668., G668.]","[nan, nan]","[nan, nan]","[nan, nan]","[Stroke, Stroke]",...,2000-03-01,stroke,2008-03-18,stroke,"[[2000-03-01 00:00:00, stroke, pri], [2008-03-...",[],False,2,2,96.560504
53316,6019969,[],"[2, 2, 2, 2, 2, 2, 2, 2, 2]","[17/04/2015, 12/05/2015, 14/05/2015, 19/05/201...","[G5730, G5730, G5730, G5730, G5730, G5730, G57...","[nan, nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan, nan]","[Afib, Afib, Afib, Afib, Afib, Afib, Afib, Afi...",...,2015-04-17,afib,NaT,NaN,"[[2015-04-17 00:00:00, afib, pri], [2015-05-12...",[],False,9,9,NaN
53318,6020725,[],"[3, 3]","[01/01/1993, 18/09/2003]","[nan, nan]","[G66.., XE0VK]","[nan, nan]","[nan, nan]","[nan, nan]","[Stroke, TIA]",...,1993-01-01,stroke,2003-09-18,tia,"[[1993-01-01 00:00:00, stroke, pri], [2003-09-...",[],False,2,2,128.528307
53320,6021143,[],"[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...","[20/01/2005, 11/02/2005, 07/04/2005, 21/11/200...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[X00DW, X00DW, X00DW, X00DW, X00DW, X00DW, X00...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, TIA, ...",...,2005-01-20,tia,2005-02-11,tia,"[[2005-01-20 00:00:00, tia, pri], [2005-02-11 ...",[],False,19,19,0.722807